"""event group optional, per-device group link

Revision ID: 695cfb1b0d3c
Revises: 6780eb253ed8
Create Date: 2026-08-10 14:06:45.730293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '695cfb1b0d3c'
down_revision: Union[str, Sequence[str], None] = '6780eb253ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_key_event_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_api_key_event_types_group_id'), ['group_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_api_key_event_types_group_id_groups'), 'groups', ['group_id'], ['id'])

    with op.batch_alter_table('event_types', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###

    # ── ย้ายค่าเดิมขึ้นมาที่ระดับ "อุปกรณ์+เหตุการณ์" ────────────────────────
    # ก่อนหน้านี้กลุ่มผู้รับผูกอยู่ที่ event type อย่างเดียว การจับคู่ที่มีอยู่แล้วทุกคู่
    # จึงใช้กลุ่มของ event type นั้นโดยปริยาย — เติมค่านั้นลงคอลัมน์ใหม่ให้ตรงกัน
    #
    # ไม่เติมก็ยังทำงานถูก (โค้ดถอยไปใช้กลุ่มเริ่มต้นของ event type อยู่แล้ว) แต่หน้าเว็บ
    # จะโชว์ช่องเลือกกลุ่มเป็นค่าว่างทั้งที่ระบบโทรหากลุ่มนั้นจริงๆ ซึ่งอ่านแล้วเข้าใจผิดได้
    # ว่ายังไม่ได้ตั้ง แล้วเผลอไปตั้งเป็นกลุ่มอื่นโดยไม่รู้ว่าของเดิมคืออะไร
    op.execute(
        """
        UPDATE api_key_event_types
           SET group_id = (
               SELECT group_id FROM event_types
                WHERE event_types.id = api_key_event_types.event_type_id
           )
         WHERE group_id IS NULL
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_types', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('api_key_event_types', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_api_key_event_types_group_id_groups'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_api_key_event_types_group_id'))
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
