"""keep event type snapshot on call jobs, set null on delete

Revision ID: eee2373d7984
Revises: e4a70c44384f
Create Date: 2026-08-10 15:28:07.105850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eee2373d7984'
down_revision: Union[str, Sequence[str], None] = 'e4a70c44384f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_type_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('event_type_name', sa.String(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_call_jobs_event_type_id_event_types'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_call_jobs_event_type_id_event_types'), 'event_types', ['event_type_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###

    # เติม snapshot ให้ประวัติเก่าที่มีอยู่แล้ว จากประเภทเหตุการณ์ที่ยังผูกอยู่
    # ถ้าไม่เติม ประวัติเก่าจะแสดงชื่อเหตุการณ์เป็นค่าว่างทันทีที่ประเภทนั้นถูกลบ
    # ทั้งที่ตอนนี้ยังอ่านได้อยู่ — ต้องเก็บไว้ก่อนที่ข้อมูลจะหายไป
    op.execute(
        """
        UPDATE call_jobs
           SET event_type_code = (SELECT code         FROM event_types WHERE event_types.id = call_jobs.event_type_id),
               event_type_name = (SELECT display_name FROM event_types WHERE event_types.id = call_jobs.event_type_id)
         WHERE event_type_id IS NOT NULL AND event_type_code IS NULL
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_call_jobs_event_type_id_event_types'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_call_jobs_event_type_id_event_types'), 'event_types', ['event_type_id'], ['id'])
        batch_op.drop_column('event_type_name')
        batch_op.drop_column('event_type_code')

    # ### end Alembic commands ###
