"""initial schema

Revision ID: 5ca0b780423c
Revises: 
Create Date: 2026-07-26 23:05:58.508873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca0b780423c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_prefix', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.String(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_prefix'), ['key_prefix'], unique=False)

    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_retry_count', sa.Integer(), nullable=True),
    sa.Column('call_retry_delay_seconds', sa.Integer(), nullable=True),
    sa.Column('call_ring_timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('sms_fallback_enabled', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('phone_number_masked', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_logs'))
    )
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_logs_job_id'), ['job_id'], unique=False)

    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
    sa.UniqueConstraint('name', name=op.f('uq_groups_name'))
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_id'), ['id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_contacts_group_id_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_id'), ['id'], unique=False)

    op.create_table('event_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_event_types_group_id_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_types'))
    )
    with op.batch_alter_table('event_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_types_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_event_types_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_types_id'), ['id'], unique=False)

    op.create_table('api_key_event_types',
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], name=op.f('fk_api_key_event_types_api_key_id_api_keys'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], name=op.f('fk_api_key_event_types_event_type_id_event_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('api_key_id', 'event_type_id', name=op.f('pk_api_key_event_types'))
    )
    op.create_table('call_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('priority_group', sa.String(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('source_device', sa.String(), nullable=True),
    sa.Column('contact_index', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'IN_PROGRESS', 'CONNECTED', 'NO_ANSWER', 'BUSY', 'RETRYING', 'ESCALATED', 'SMS_FALLBACK_SENT', 'FAILED', 'CANCELLED', name='callstatus'), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], name=op.f('fk_call_jobs_api_key_id_api_keys'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], name=op.f('fk_call_jobs_event_type_id_event_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_jobs'))
    )
    with op.batch_alter_table('call_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_jobs_api_key_id'), ['api_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_jobs_next_attempt_at'), ['next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_jobs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_call_jobs_next_attempt_at'))
        batch_op.drop_index(batch_op.f('ix_call_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_call_jobs_created_at'))
        batch_op.drop_index(batch_op.f('ix_call_jobs_api_key_id'))

    op.drop_table('call_jobs')
    op.drop_table('api_key_event_types')
    with op.batch_alter_table('event_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_types_id'))
        batch_op.drop_index(batch_op.f('ix_event_types_group_id'))
        batch_op.drop_index(batch_op.f('ix_event_types_code'))

    op.drop_table('event_types')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_group_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_id'))

    op.drop_table('groups')
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_logs_job_id'))
        batch_op.drop_index(batch_op.f('ix_call_logs_id'))

    op.drop_table('call_logs')
    op.drop_table('app_settings')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_keys_id'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
