import { useState, useEffect, createContext, useContext, type ReactNode } from "react";
import type { Lang } from "../types";

// ─── Translations ─────────────────────────────────────────────────────────────

export const TR = {
  th: {
    app_name: "Voice Alert", app_version: "ผู้ใช้เดียว · self-hosted",
    nav_overview: "ภาพรวม", nav_queue: "คิวการโทร", nav_history: "ประวัติการโทร",
    nav_settings: "การตั้งค่า", nav_contacts: "กลุ่มผู้รับ", nav_api: "API guide", nav_logout: "ออกจากระบบ",
    nav_event_types: "ประเภทเหตุการณ์", nav_api_keys: "API keys",
    tab_overview: "ภาพรวม", tab_queue: "คิว", tab_history: "ประวัติ", tab_settings: "ตั้งค่า", tab_contacts: "กลุ่ม",
    tab_event_types: "เหตุการณ์", tab_api_keys: "API keys",
    login_sub: "แจ้งเตือน IoT ด้วยการโทรผ่าน 4G", login_username: "ชื่อผู้ใช้", login_password: "รหัสผ่าน",
    login_submit: "เข้าสู่ระบบ", login_error: "กรุณากรอกข้อมูลให้ครบ", login_invalid: "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง",
    overview_title: "ภาพรวมระบบ", overview_sub: "สถานะระบบและสรุปการโทรวันนี้",
    stat_calls: "โทรออกวันนี้", stat_calls_sub: "ตั้งแต่เที่ยงคืน",
    stat_rate: "อัตราสำเร็จ", stat_rate_sub: (ok: number, total: number) => `${ok} จาก ${total} สาย`,
    stat_rate_none: "ยังไม่มีสายวันนี้",
    stat_queue: "รอในคิว", stat_queue_sub: "งาน active",
    recent_title: "กิจกรรมล่าสุด", recent_sub: "5 รายการล่าสุด", realtime: "ข้อมูลเรียลไทม์", sample_data: "ข้อมูลตัวอย่าง",
    outcome_title: "ผลการโทรวันนี้", outcome_empty: "ยังไม่มีสายวันนี้",
    outcome_sub: (n: number) => `จากทั้งหมด ${n} สาย`,
    system_info_title: "System info", system_info_worker: "Call worker",
    system_info_worker_running: "กำลังทำงาน", system_info_worker_stopped: "ยังไม่เริ่มทำงาน",
    system_info_uptime: "Uptime", system_info_gsm: "GSM module", system_info_gsm_port: "พอร์ต",
    system_info_db_size: "ขนาดฐานข้อมูล", system_info_version: "เวอร์ชัน",
    device_pi_label: "Raspberry Pi", device_gsm_label: "GSM Module",
    device_view_detail: "แตะเพื่อดูรายละเอียด",
    gsm_detail_title: "รายละเอียด GSM Module", gsm_mode_label: "โหมดเครือข่าย", gsm_operator_label: "เครือข่าย",
    gsm_signal_label: "ความแรงสัญญาณ", gsm_signal_unknown: "ไม่ทราบ", gsm_no_operator: "ไม่มีสัญญาณ",
    gsm_signal_excellent: "ดีมาก", gsm_signal_good: "ดี", gsm_signal_fair: "พอใช้", gsm_signal_poor: "อ่อน",
    gsm_offline_note: "GSM module ยังไม่เชื่อมต่อ",
    gsm_status_ok: "ออนไลน์", gsm_status_error: "สัญญาณขัดข้อง",
    pi_detail_title: "รายละเอียด Raspberry Pi", pi_cpu_label: "การใช้งาน CPU", pi_ram_label: "การใช้งาน RAM",
    pi_temp_label: "อุณหภูมิ CPU", pi_temp_unavailable: "อ่านค่าไม่ได้บนเครื่องนี้",
    widget_title: "สถานะการโทรแจ้งเตือน",
    widget_idle: "รอการเชื่อมต่อ", widget_active: "กำลังโทร...", widget_success: "โทรสำเร็จ", widget_failed: "ไม่รับสาย — กำลัง retry",
    queue_title: "คิวการโทร", queue_sub: "งานที่รอดำเนินการและกำลังทำงาน", queue_live: "Live",
    queue_empty: "คิวว่างเปล่า", queue_empty_sub: "ไม่มีงานรอดำเนินการในขณะนี้",
    col_id: "Job ID", col_group: "กลุ่ม", col_phone: "เบอร์โทร", col_status: "สถานะ",
    col_retry: "retry", col_created: "สร้างเมื่อ", col_datetime: "วันที่-เวลา", col_note: "หมายเหตุ",
    history_title: "ประวัติการโทร", history_records: (n: number) => `รายการโทรทั้งหมด ${n} รายการ`,
    search_ph: "ค้นหาข้อความหรือ job ID…", search_short: "ค้นหา…",
    all_status: "สถานะทั้งหมด", all_groups: "กลุ่มทั้งหมด", clear: "ล้าง",
    filters_btn: "ตัวกรอง", filters_title: "ตัวกรอง", filters_apply: "ใช้ตัวกรอง", filters_reset: "ล้างตัวกรอง",
    no_data: "ไม่พบข้อมูล", page_of: (p: number, t: number) => `หน้า ${p} จาก ${t}`,
    prev: "← ก่อนหน้า", next: "ถัดไป →",
    filter_status: "สถานะ", filter_group: "กลุ่มผู้รับ",
    settings_title: "การตั้งค่า", settings_sub: "พฤติกรรมการโทรและ fallback",
    retry_section: "พฤติกรรม retry", retry_section_sub: "กำหนดจำนวนครั้งและระยะเวลาในการโทรซ้ำ",
    retry_count: "จำนวนครั้งที่โทรซ้ำ", retry_count_sub: "โทรซ้ำสูงสุดกี่ครั้งก่อนจะถือว่าล้มเหลว",
    retry_delay: "เวลารอก่อนโทรซ้ำ", retry_delay_sub: "วินาทีที่รอก่อนโทรซ้ำ",
    ring_timeout: "เวลารอให้รับสาย", ring_timeout_sub: "วินาทีที่รอสายก่อนตัดว่าไม่รับ",
    unit_times: "ครั้ง", unit_seconds: "วินาที",
    setup_title: "ตั้งค่าการแจ้งเตือน",
    setup_sub: "ตั้งค่าว่าใครยิงอะไรเข้ามาได้ และยิงแล้วโทรหาใคร",
    setup_tab_devices: "อุปกรณ์ & key", setup_tab_events: "ประเภทเหตุการณ์", setup_tab_contacts: "กลุ่มผู้รับ",
    setup_flow_title: "ลำดับการตั้งค่า",
    setup_step_group: "กลุ่มผู้รับ", setup_step_group_hint: "เบอร์ที่จะโทรหา เรียงตามลำดับ",
    setup_step_event: "ประเภทเหตุการณ์", setup_step_event_hint: "ข้อความที่จะพูด + โทรหากลุ่มไหน",
    setup_step_device: "อุปกรณ์ & key", setup_step_device_hint: "ใครยิงเข้ามาได้ และยิงอะไรได้บ้าง",
    setup_count: (n: number) => `${n} รายการ`,
    setup_none: "ยังไม่มี",
    et_group_label: "กลุ่มผู้รับเริ่มต้น (ไม่บังคับ)",
    et_group_optional_none: "— ไม่ระบุ (ตั้งที่อุปกรณ์) —",
    et_group_optional_hint: "ปกติไม่ต้องเลือก — กลุ่มที่จะโทรจริงตั้งแยกรายอุปกรณ์ที่หน้าอุปกรณ์ & key ช่องนี้ใช้เฉพาะตอนกดทดสอบจากหน้าเว็บ",
    dev_call_group: "โทรหากลุ่ม", dev_call_group_none: "— เลือกกลุ่ม —",
    dev_call_group_missing: "ยังไม่ได้เลือกกลุ่ม",
    dev_key_full: "key เต็มของอุปกรณ์นี้",
    dev_key_locked: "อุปกรณ์นี้สร้างก่อนระบบเก็บ key ไว้ให้ดูซ้ำได้ — เห็นได้แค่ตัวหน้า ถ้าต้องใช้ key เต็มต้องสร้างอุปกรณ์ใหม่",
    dev_api_title: "วิธียิงเข้ามาจากอุปกรณ์นี้",
    dev_api_sub: "ทุกอย่างที่บอร์ดต้องใช้ อยู่ครบในนี้แล้ว ไม่ต้องเปิดหน้า API guide",
    dev_api_key_note: "คำสั่งนี้มี key จริงอยู่แล้ว ก็อปไปวางใน firmware ได้เลย — อย่าแชร์ให้คนอื่นหรือ commit ขึ้น repo สาธารณะ",
    dev_api_no_event: "เลือกเหตุการณ์ที่อุปกรณ์นี้ยิงได้ก่อน แล้วตัวอย่างจะเปลี่ยนตาม",
    dev_api_ok: "ตอบกลับเมื่อสำเร็จ", dev_api_err: "ตอบกลับเมื่อผิดพลาด",
    dev_api_status: "รหัสที่เจอบ่อย",
    dev_api_status_401: "key ผิด หรืออุปกรณ์ถูกลบไปแล้ว",
    dev_api_status_403: "key ถูก แต่ยังไม่ได้ให้สิทธิ์ยิงเหตุการณ์นี้ — ติ๊กเพิ่มด้านซ้าย",
    dev_api_status_404: "ไม่มีรหัสเหตุการณ์นี้ในระบบ",
    dev_api_status_422: "ไม่ได้ส่ง header X-API-Key หรือรูปแบบ JSON ผิด",
    setup_ready: "พร้อมรับแจ้งเตือนแล้ว",
    setup_blocked: (what: string) => `ยังใช้งานไม่ได้ — ต้องมี${what}ก่อน`,
    cfg_saving: "กำลังบันทึก…", cfg_saved: "บันทึกแล้ว", cfg_save_failed: "บันทึกไม่สำเร็จ",
    gsm_restart: "รีสตาร์ทโมดูล", gsm_restarting: "กำลังรีสตาร์ท…",
    gsm_restart_confirm_title: "รีสตาร์ทโมดูล 4G?",
    gsm_restart_confirm_body: "โมดูลจะปิด-เปิดคลื่นวิทยุแล้วหาเครือข่ายใหม่ ใช้เวลาราว 10-30 วินาที ระหว่างนี้โทรออกไม่ได้ · งานที่รอในคิวจะถูกโทรต่อให้เองหลังเสร็จ · ระบบจะไม่ตัดสายที่กำลังคุยอยู่ (รอจนสายจบก่อนเสมอ)",
    gsm_restart_hint: "ใช้เมื่อสัญญาณหาย หาเครือข่ายไม่เจอ หรือโมดูลไม่ตอบสนอง",
    gsm_restart_ok: "รีสตาร์ทโมดูลสำเร็จ กลับเข้าเครือข่ายแล้ว",
    gsm_restart_failed: "รีสตาร์ทแล้วแต่ยังไม่กลับเข้าเครือข่าย — ลองเช็คซิม/สายอากาศ",
    gsm_restart_sent: "ส่งคำสั่งแล้ว รอโมดูลกลับมาสักครู่",
    retry_count_help: "ถ้าเบอร์แรกไม่รับ จะโทรซ้ำเบอร์เดิมอีกกี่ครั้ง ครบแล้วจึงข้ามไปเบอร์ถัดไปในกลุ่ม",
    retry_count_example: (n: number) =>
      n === 0
        ? "ตั้ง 0 = ไม่โทรซ้ำเลย ไม่รับปุ๊บข้ามไปเบอร์ถัดไปทันที (เหมาะกับเหตุด่วนที่ต้องหาคนรับให้เร็วที่สุด)"
        : `ตั้ง ${n} → โทรเบอร์แรกทั้งหมด ${n + 1} ครั้ง (ครั้งแรก + ซ้ำอีก ${n}) ถ้ายังไม่รับจึงไปเบอร์ที่ 2`,
    retry_delay_help: "รอกี่วินาทีก่อนโทรซ้ำ ระหว่างรอ ระบบไม่ได้อยู่เฉยๆ — เอาเวลาไปโทรงานอื่นในคิวต่อได้เลย",
    retry_delay_example: (n: number) => `ตั้ง ${n} → ไม่รับตอน 10:00:00 จะโทรซ้ำอีกทีตอน 10:00:${String(n % 60).padStart(2, "0")}`,
    ring_timeout_help: "ปล่อยให้ปลายทางดังนานแค่ไหนก่อนตัดว่าไม่รับ สั้นไปคนหยิบไม่ทัน ยาวไปคิวงานถัดไปเดินช้า",
    ring_timeout_example: (n: number) => `ตั้ง ${n} → ดัง ${n} วินาทีแล้วยังไม่รับ = วางสายเอง นับเป็น "ไม่รับสาย" 1 ครั้ง`,
    call_budget_title: "รวมแล้วเบอร์หนึ่งใช้เวลาสูงสุด",
    call_budget: (sec: number, tries: number) =>
      `${sec} วินาที (~${Math.ceil(sec / 60)} นาที) ต่อ 1 เบอร์ — โทร ${tries} ครั้ง แล้วจึงข้ามไปเบอร์ถัดไป`,
    save_btn: "บันทึกการตั้งค่า", save_ok: "บันทึกการตั้งค่าสำเร็จ",
    contacts_title: "กลุ่มผู้รับการแจ้งเตือน", contacts_sub: "จัดการเบอร์โทรตามลำดับ escalation",
    add_group: "เพิ่มกลุ่ม", new_group: "กลุ่มใหม่", new_group_ph: "เช่น database_team", create: "สร้าง",
    no_phones: "ยังไม่มีเบอร์โทร — เพิ่มด้านล่าง", phone_ph: "+66812345678",
    phones_count: (n: number) => `${n} เบอร์โทร`,
    group_delete_confirm: "ลบกลุ่มนี้? เบอร์โทรทั้งหมดในกลุ่มจะถูกลบด้วย",
    api_title: "API guide", api_sub: "เอกสารอ้างอิงสำหรับ integration กับระบบภายนอก",
    api_key_section: "API key", api_key_warn: "อย่าเปิดเผย API key นี้ในที่สาธารณะ ส่ง key ผ่าน environment variable หรือ secret manager เสมอ",
    copy: "คัดลอก", copied: "คัดลอกแล้ว",
    copy_failed: "คัดลอกไม่สำเร็จ — กดค้างที่ข้อความแล้วคัดลอกเองได้",
    endpoint_title: "POST /notify",
    endpoint_desc: "ส่งคำสั่งโทรแจ้งเตือนตามรหัส event type ระบบจะ queue งานและโทรตามลำดับ escalation ของกลุ่มที่ผูกไว้",
    curl_title: "ตัวอย่าง curl request", resp_title: "ตัวอย่าง response",
    manage_keys_hint: "จัดการ API key จริงได้ที่หน้า",
    api_quickstart_title: "เริ่มต้นใช้งานใน 3 ขั้นตอน",
    qs_step1_title: "สร้างประเภทเหตุการณ์", qs_step1_desc: "กำหนดรหัส ข้อความ และกลุ่มผู้รับ",
    qs_step2_title: "สร้าง API key", qs_step2_desc: "สำหรับให้ระบบภายนอกยืนยันตัวตน",
    qs_step3_title: "เรียก endpoint", qs_step3_desc: "ยิง POST /notify พร้อม API key",
    request_body_title: "Request body", response_title: "Response",
    resp_field_job_id_desc: "หมายเลขงานที่เข้าคิว ใช้ตรวจสอบสถานะภายหลังได้",
    resp_field_status_desc: "สถานะเริ่มต้นของงาน (มักเป็น queued)",
    resp_field_message_desc: "ข้อความยืนยันสำหรับแสดงผล",
    code_examples_title: "ตัวอย่างโค้ด", error_resp_title: "ตัวอย่าง response เมื่อเกิดข้อผิดพลาด",
    base_url_note: "แทนที่ https://your-pi.local ด้วยที่อยู่จริงของอุปกรณ์ในเครือข่ายของคุณ",
    base_url_label: "Base URL", request_body_json_label: "Request body (JSON)",
    col_parameter: "พารามิเตอร์", col_required: "จำเป็น", col_type: "ชนิดข้อมูล", col_description: "คำอธิบาย",
    status_codes_title: "HTTP status codes",
    status_200_desc: "Request สำเร็จ งานถูก queue เรียบร้อยแล้ว",
    status_400_desc: "ข้อมูลถูกต้องตามรูปแบบแต่ประมวลผลไม่ได้ เช่น event type ถูกปิดใช้งาน หรือขาดตัวแปรที่ template ต้องการ",
    status_401_desc: "API key ไม่ถูกต้องหรือถูกเพิกถอนแล้ว (ถ้าไม่ได้ส่ง header X-API-Key มาเลยจะได้ 422 แทน)",
    status_404_desc: "ไม่พบ event type ตามรหัสที่ระบุ",
    status_422_desc: "รูปแบบข้อมูลไม่ถูกต้อง เช่น ไม่ได้ส่ง event_type_code มา หรือชนิดข้อมูลผิด (ตรวจสอบอัตโนมัติ)",
    status_500_desc: "ข้อผิดพลาดภายในระบบ กรุณาลองใหม่อีกครั้ง",
    badge_success: "สำเร็จ", badge_failed: "ล้มเหลว", badge_retrying: "กำลัง retry",
    badge_calling: "กำลังโทร", badge_queued: "รอคิว",
    badge_no_answer: "ไม่รับสาย", badge_busy: "สายไม่ว่าง", badge_escalated: "ไล่เบอร์ถัดไป",
    pi_label: "Raspberry Pi", tower_label: "สัญญาณ 4G", phone_label: "โทรแจ้งเตือน",
    required: "required", optional: "optional",
    loading: "กำลังโหลด...", error_generic: "เกิดข้อผิดพลาด กรุณาลองใหม่", retry_action: "ลองอีกครั้ง",
    cancel: "ยกเลิก", save: "บันทึก", saving: "กำลังบันทึก...", delete: "ลบ", edit: "แก้ไข", close: "ปิด",
    confirm: "ยืนยัน", yes_delete: "ใช่ ลบเลย",
    event_types_title: "ประเภทเหตุการณ์", event_types_sub: "กำหนดรหัสเหตุการณ์ ข้อความ และกลุ่มผู้รับสำหรับระบบภายนอก",
    add_event_type: "เพิ่มประเภทเหตุการณ์", new_event_type: "ประเภทเหตุการณ์ใหม่", edit_event_type: "แก้ไขประเภทเหตุการณ์",
    code_label: "รหัส (code)", code_ph: "เช่น power_outage", code_hint: "ตัวพิมพ์เล็ก ตัวเลข และ _ เท่านั้น แก้ไขไม่ได้ภายหลัง",
    display_name_label: "ชื่อที่แสดง", display_name_ph: "เช่น ไฟดับ",
    message_template_label: "ข้อความ template", message_template_ph: "เช่น ไฟดับที่ {location} เวลา {value}",
    message_template_hint: "ใช้ {ชื่อตัวแปร} แทนค่าที่จะกำหนดตอนส่งจริง",
    group_label: "กลุ่มผู้รับ", active_label: "ใช้งานอยู่",
    col_code: "รหัส", col_name: "ชื่อที่แสดง", col_active: "สถานะ", col_actions: "จัดการ",
    send_test: "ส่งทดสอบ", test_dialog_title: "ส่งการแจ้งเตือนทดสอบ",
    test_variables_label: "ตัวแปร (variables)", test_variables_hint: "รูปแบบ key=value หนึ่งค่าต่อบรรทัด",
    test_message_override_label: "ข้อความ (ไม่บังคับ — เว้นว่างเพื่อใช้ template)",
    send: "ส่ง", sending: "กำลังส่ง...", test_sent_ok: (id: number) => `ส่งคำขอทดสอบแล้ว — job #${id}`,
    delete_confirm_title: "ยืนยันการลบ", event_type_delete_confirm: "ลบประเภทเหตุการณ์นี้?",
    code_exists_error: "รหัสนี้มีอยู่แล้ว", no_event_types: "ยังไม่มีประเภทเหตุการณ์",
    api_keys_title: "API keys", api_keys_sub: "จัดการ key สำหรับระบบภายนอกที่เรียก /notify",
    add_key: "สร้าง key ใหม่", new_key_name_label: "ชื่อ key", new_key_name_ph: "เช่น Monitoring board",
    key_created_title: "สร้าง API key สำเร็จ", key_created_warning: "คัดลอก key นี้เก็บไว้ตอนนี้ — จะไม่แสดงให้เห็นอีกเป็นครั้งที่สอง",
    key_prefix_label: "Key", last_used_label: "ใช้ล่าสุด", created_label: "สร้างเมื่อ", revoked_label: "เพิกถอนเมื่อ",
    status_active: "ใช้งานอยู่", status_revoked: "ถูกเพิกถอน", never: "ไม่เคยใช้",
    revoke: "ลบ", revoke_confirm_title: "ยืนยันการลบอุปกรณ์", revoke_confirm_body: "ลบอุปกรณ์นี้ออกจากระบบ? key จะใช้ไม่ได้ทันทีและเอากลับไม่ได้ (ประวัติการโทรเดิมยังอยู่)",
    no_api_keys: "ยังไม่มี API key",
    filter_date_from: "ตั้งแต่วันที่", filter_date_to: "ถึงวันที่",
    toast_created: "สร้างสำเร็จ", toast_updated: "แก้ไขสำเร็จ", toast_deleted: "ลบสำเร็จ",

    // ─── หน้าอุปกรณ์ (1 key = 1 อุปกรณ์) ───
    devices_title: "อุปกรณ์ & key",
    devices_sub: "1 key ต่อ 1 อุปกรณ์ — ฝัง key ในบอร์ดครั้งเดียว ที่เหลือแก้จากหน้านี้",
    devices_summary: (n: number, active: number) => `${n} อุปกรณ์ · ใช้งานอยู่ ${active}`,
    add_device: "เพิ่มอุปกรณ์",
    device_name_label: "ชื่ออุปกรณ์",
    device_name_ph: "เช่น โหนดตึก A ชั้น 3",
    device_name_hint: "ชื่อนี้จะถูกพูดในสายแทน {device} — เปลี่ยนทีหลังได้ ไม่ต้องแฟลชบอร์ดใหม่",
    device_configure: "ตั้งค่า",
    device_test_call: "ทดสอบโทร",
    device_remove: "ลบอุปกรณ์",
    device_remove_confirm: "กดอีกครั้งเพื่อยืนยัน",
    device_online: "เพิ่งส่งข้อมูล",
    device_never_used: "ยังไม่เคยส่งข้อมูล",
    devices_empty_title: "ยังไม่มีอุปกรณ์",
    devices_empty_body: "สร้าง key แรกเพื่อให้บอร์ดยิงแจ้งเตือนเข้ามาได้",

    allowed_events_label: "การแจ้งเตือนที่ยิงได้",
    allowed_events_none: "ยังไม่ได้ให้สิทธิ์ — อุปกรณ์นี้ยิงอะไรเข้ามาก็จะถูกปฏิเสธ (403)",
    allowed_events_pick: "เลือกประเภทเหตุการณ์ที่อุปกรณ์นี้ยิงได้",
    allowed_events_empty_hint: "ยังไม่มีประเภทเหตุการณ์ในระบบ — สร้างที่หน้าประเภทเหตุการณ์ก่อน",

    key_once_title: "key นี้แสดงครั้งเดียว",
    key_once_body: "คัดลอกไปฝังใน firmware ตอนนี้ — ปิดหน้าต่างนี้แล้วจะดูอีกไม่ได้ (ระบบเก็บแค่ค่า hash)",
    key_no_copy_hint: "ดูได้แค่ส่วนหน้าของ key เพราะระบบเก็บแค่ hash ไม่ได้เก็บ key เต็ม",
    save_and_configure: "บันทึกแล้วไปตั้งค่า",
    save_only: "บันทึกไว้ก่อน",
    done: "เสร็จแล้ว",

    device_config_title: "ตั้งค่าอุปกรณ์",
    what_will_happen: "ถ้าอุปกรณ์นี้ยิงเข้ามาจะเกิดอะไร",
    what_will_happen_empty: "ยังไม่ได้ให้สิทธิ์การแจ้งเตือนใดๆ",
    payload_title: "payload ที่อุปกรณ์ต้องส่ง",
    shared_config_note: "เบอร์ผู้รับและข้อความเป็นค่าที่แชร์กันตามประเภทเหตุการณ์ — แก้ที่เดียวมีผลกับทุกอุปกรณ์ที่ใช้ประเภทนั้น",
    goto_event_types: "แก้ประเภทเหตุการณ์",
    goto_contacts: "แก้กลุ่มผู้รับ",
    // ─── Signal Flow Monitor ───
    flow_title: "ติดตามสัญญาณแจ้งเตือน",
    flow_node_api: "API Gateway",
    flow_node_pi: "Raspberry Pi",
    flow_node_antenna: "เสาสัญญาณ 4G",
    flow_node_phone: "โทรศัพท์",
    flow_step_preparing: "กำลังแปลงข้อความเป็นเสียง",
    flow_step_uploading: "กำลังส่งไฟล์เสียงเข้าโมดูล",
    flow_step_dialing: "กำลังโทรออก รอปลายสายรับ",
    flow_step_playing: "รับสายแล้ว กำลังพูดข้อความ",
    flow_step_waiting_retry: "สายไม่สำเร็จ กำลังรอโทรซ้ำ",
    flow_result_rejected: "ปลายสายกดปฏิเสธ — รอโทรซ้ำ",
    flow_result_no_answer: "ไม่มีใครรับสาย — รอโทรซ้ำ",
    flow_result_busy: "สายไม่ว่าง — รอโทรซ้ำ",
    flow_cap_received: "รับข้อมูลแล้ว",
    flow_cap_tts: "กำลังแปลงเสียง",
    flow_cap_upload: "กำลังส่งเข้าโมดูล",
    flow_cap_dialing: "กำลังต่อปลายสาย",
    flow_cap_playing: "กำลังพูดข้อความ",
    flow_cap_retry: "รอโทรซ้ำ",
    flow_state_idle: "ว่าง",
    flow_state_calling: "กำลังต่อสาย",
    flow_state_ringing: "กำลังเรียก / รอ retry",
    flow_state_success: "โทรติดแล้ว",
    flow_state_failed: "ล้มเหลว",
    flow_gsm_offline: "โมดูลยังไม่เชื่อมต่อ",
    flow_source: (n: number) => `งานในคิว ${n}`,
    flow_step_note: "จังหวะละเอียดต่อขั้น (รับ payload → ตรวจ key → สั่งโทร → ปลายทางรับ → เล่นเสียงจบ) ต้องมี endpoint GET /history/{job_id} ก่อน ตอนนี้ไล่จากสถานะของงานล่าสุดเท่านั้น",
    flow_layout_style: "รูปแบบการแสดง",
    module_ready: "ออนไลน์", module_not_ready: "ออฟไลน์", sign_out_short: "ออก",
    dash_last_update: (t: string) => `อัปเดตล่าสุด ${t}`,
    dash_refresh_every: (s: number) => `รีเฟรชอัตโนมัติทุก ${s} วิ`,
    pipe_title: "การทำงานตอนนี้", pipe_flow: "payload → ตรวจ key → เข้าคิว → โทร → ผล",
    pipe_queued: "เข้าคิว", pipe_calling: "กำลังโทร", pipe_retry: "รอโทรซ้ำ", pipe_done: "จบแล้ววันนี้",
    pipe_queued_sub: "รอ worker หยิบ", pipe_calling_sub: "กำลังต่อสาย", pipe_retry_sub: "รอรอบถัดไป", pipe_done_sub: "รวมทุกผล",
    pipe_none: "ว่าง",
    flow_signal_step: "SIGNAL STEP",
    flow_auto: "Auto", flow_demo_mode: "สาธิต", flow_incoming_requests: "INCOMING REQUESTS",
    flow_badge_working: "กำลังทำงาน", flow_badge_queued: (n: number) => `รอคิว ${n}`,
    flow_req: (n: number) => `${n} req`,
    flow_demo_note: "โหมดสาธิต — ภาพที่เห็นถูกบังคับให้แสดงสถานะนี้ ไม่ใช่สถานะจริงของระบบ",
    flow_time_unknown: "ยังไม่มีเวลาต่อขั้น",
    flow_legend_done: "ผ่านแล้ว", flow_legend_active: "กำลังทำงาน", flow_legend_ringing: "กำลังเรียกสาย",
    flow_legend_failed: "ไม่สำเร็จ", flow_legend_pending: "ยังไม่ถึง",
    flow_open_settings: "ไปหน้าตั้งค่าการโทร",
    flow_steps: ["รับคำขอ", "ตรวจสิทธิ์", "สร้างเสียงพูด", "เตรียมส่ง",
      "เชื่อมต่อโมดูล", "อัปโหลดเสียง", "กำลังโทร", "ปลายทางรับสาย"],
    flow_step_aria: (n: number, name: string) => `ขั้นตอนที่ ${n} จาก 8 · ${name}`,
    flow_all_steps_done: "ครบทั้ง 8 ขั้นตอน",
    api_base_label: "base",
    api_notes_title: "ข้อควรรู้",
    api_note_1: "ชื่ออุปกรณ์ที่ตั้งใน dashboard จะถูกพูดแทน {device} ในข้อความ — บอร์ดไม่ต้องส่งชื่อตัวเองมา",
    api_note_2: "เปลี่ยนเบอร์ผู้รับหรือข้อความทีหลังได้ โดยไม่ต้องแก้ firmware",
    api_note_3: "ถ้าได้ 403 ให้ไปเพิ่มสิทธิ์ event type ให้อุปกรณ์นั้นที่หน้าอุปกรณ์",
    api_note_4: "key แสดงครั้งเดียวตอนสร้าง ถ้าหายต้องเพิกถอนแล้วสร้างใหม่ (ต้องแฟลชบอร์ดใหม่)",
    sys_section_hw: "ฮาร์ดแวร์", sys_section_call: "ค่าการโทร", sys_section_app: "แอปและบัญชี",


    // ─── หน้าระบบ & ฮาร์ดแวร์ ───
    sys_title: "ระบบ & ฮาร์ดแวร์",
    sys_meta: "โมดูล 4G · Raspberry Pi · ค่าการโทร · บัญชี",
    sys_module_4g: "โมดูล 4G",
    sys_module_offline: "ยังไม่เชื่อมต่อ",
    sys_module_port: "พอร์ต",
    sys_module_updated: "อัปเดตล่าสุด",
    sys_pi_title: "Raspberry Pi",
    sys_call_config: "ค่าการโทร",
    sys_call_config_note: "บันทึกอัตโนมัติทุกครั้งที่แก้ · worker เห็นค่าใหม่เองภายในไม่กี่วินาที ไม่ต้อง restart",
    sys_runtime: "รันไทม์",
    sys_theme_label: "ธีมของหน้าเว็บ",
    sys_theme_to_light: "สลับเป็นสว่าง",
    sys_theme_to_dark: "สลับเป็นมืด",
    sys_missing_title: "ยังไม่มีใน backend",
    sys_missing_body: "เครดิตซิม · รีสตาร์ทโมดูล · เสียงชาย/หญิง+ความเร็ว · เปลี่ยนรหัสผ่านจากหน้าเว็บ · ออกจากระบบทุกอุปกรณ์ — ดีไซน์เผื่อไว้แต่ยังไม่มี endpoint รองรับ จึงไม่ได้ทำเป็นช่องหลอกไว้",

    // ─── หน้าประวัติการโทร (call log) ───
    log_filter_all: "ทั้งหมด",
    log_filter_ok: "โทรสำเร็จ",
    log_filter_no_answer: "ไม่รับสาย",
    log_filter_failed: "ล้มเหลว",
    log_export_csv: "ออกไฟล์ CSV",
    log_export_note: "ออกเฉพาะหน้าที่กำลังดูอยู่",
    log_date_from: "ตั้งแต่", log_date_to: "ถึง",
    log_date_today: "วันนี้", log_date_7d: "7 วัน", log_date_30d: "30 วัน",
    log_date_all: "ทุกช่วงเวลา", log_date_custom: "กำหนดเอง",
    log_group_status: "ผลการโทร", log_group_range: "ช่วงเวลา",
    log_col_device: "อุปกรณ์",
    log_col_event: "เหตุการณ์",
    log_empty: "ไม่พบรายการตามเงื่อนไขที่เลือก",
    log_range: (from: number, to: number, total: number) => `${from}–${to} / ${total}`,

    // ─── หน้าภาพรวม (dashboard) ───
    dash_auto_refresh: "รีเฟรชอัตโนมัติทุก 5 วิ",
    dash_signal_4g: "สัญญาณ 4G",
    dash_success_fail: "สำเร็จ / ล้มเหลว",
    dash_tap_row_hint: "แตะแถวเพื่อดูรายละเอียด",
    dash_view_all: "ดูทั้งหมด",
    dash_calls_24h: "การโทร 24 ชั่วโมง",
    dash_spoken: "ข้อความที่พูดในสาย",
    dash_no_events: "ยังไม่มีเหตุการณ์",
    dash_detail_note: "รายละเอียดครบทุกขั้น (รับ payload → ตรวจ key → สั่งโทร → ปลายทางรับ → เล่นเสียงจบ) ต้องมี endpoint GET /history/{job_id} ก่อน ตอนนี้แสดงเท่าที่ /history คืนมาได้",
    dash_last_attempt: "ผลครั้งล่าสุด",
    dash_retry_count: "โทรซ้ำไปแล้ว",
    dash_contact_index: "เบอร์ลำดับที่",
    dash_hours_capped: "นับจากรายการล่าสุด 100 รายการของวันนี้",

    retry_summary: (count: number, delay: number) => `ไม่รับสาย → โทรซ้ำ ${count} ครั้ง ห่างครั้งละ ${delay} วินาที`,
    escalate_summary: "ครบรอบแล้วยังไม่รับ → ไล่โทรเบอร์ถัดไปในกลุ่ม",
  },
  en: {
    app_name: "Voice Alert", app_version: "ผู้ใช้เดียว · self-hosted",
    nav_overview: "Overview", nav_queue: "Call Queue", nav_history: "Call History",
    nav_settings: "Settings", nav_contacts: "Contacts", nav_api: "API Guide", nav_logout: "Log out",
    nav_event_types: "Event Types", nav_api_keys: "API Keys",
    tab_overview: "Overview", tab_queue: "Queue", tab_history: "History", tab_settings: "Settings", tab_contacts: "Contacts",
    tab_event_types: "Events", tab_api_keys: "API Keys",
    login_sub: "IoT Emergency Notification System", login_username: "Username", login_password: "Password",
    login_submit: "Sign in", login_error: "Please fill in all fields", login_invalid: "Invalid username or password",
    overview_title: "System overview", overview_sub: "System status and today's call summary",
    stat_calls: "Calls today", stat_calls_sub: "since midnight",
    stat_rate: "Success rate", stat_rate_sub: (ok: number, total: number) => `${ok} of ${total} calls`,
    stat_rate_none: "No calls yet today",
    stat_queue: "In queue", stat_queue_sub: "active jobs",
    recent_title: "Recent activity", recent_sub: "Last 5 entries", realtime: "Real-time", sample_data: "Sample data",
    outcome_title: "Today's call outcomes", outcome_empty: "No calls yet today",
    outcome_sub: (n: number) => `out of ${n} calls`,
    system_info_title: "System info", system_info_worker: "Call worker",
    system_info_worker_running: "Running", system_info_worker_stopped: "Not started",
    system_info_uptime: "Uptime", system_info_gsm: "GSM module", system_info_gsm_port: "Port",
    system_info_db_size: "Database size", system_info_version: "Version",
    device_pi_label: "Raspberry Pi", device_gsm_label: "GSM Module",
    device_view_detail: "Tap for details",
    gsm_detail_title: "GSM Module Details", gsm_mode_label: "Network mode", gsm_operator_label: "Carrier",
    gsm_signal_label: "Signal strength", gsm_signal_unknown: "Unknown", gsm_no_operator: "No signal",
    gsm_signal_excellent: "Excellent", gsm_signal_good: "Good", gsm_signal_fair: "Fair", gsm_signal_poor: "Weak",
    gsm_offline_note: "GSM module is not connected",
    gsm_status_ok: "Online", gsm_status_error: "Signal issue",
    pi_detail_title: "Raspberry Pi Details", pi_cpu_label: "CPU usage", pi_ram_label: "RAM usage",
    pi_temp_label: "CPU temperature", pi_temp_unavailable: "Not available on this device",
    widget_title: "Call alert status",
    widget_idle: "Waiting", widget_active: "Calling...", widget_success: "Call succeeded", widget_failed: "No answer — retrying",
    queue_title: "Call Queue", queue_sub: "Pending and in-progress jobs", queue_live: "Live",
    queue_empty: "Queue is empty", queue_empty_sub: "No jobs pending at this time",
    col_id: "Job ID", col_group: "Group", col_phone: "Phone", col_status: "Status",
    col_retry: "Retries", col_created: "Created", col_datetime: "Date / Time", col_note: "Note",
    history_title: "Call History", history_records: (n: number) => `${n} records total`,
    search_ph: "Search message or job ID…", search_short: "Search…",
    all_status: "All statuses", all_groups: "All groups", clear: "Clear",
    filters_btn: "Filters", filters_title: "Filters", filters_apply: "Apply filters", filters_reset: "Clear filters",
    no_data: "No records found", page_of: (p: number, t: number) => `Page ${p} of ${t}`,
    prev: "← Previous", next: "Next →",
    filter_status: "Status", filter_group: "Recipient group",
    settings_title: "Settings", settings_sub: "Call behavior and fallback options",
    retry_section: "Retry behavior", retry_section_sub: "Configure retry count and timing",
    retry_count: "Retry count", retry_count_sub: "Maximum retries before marking as failed",
    retry_delay: "Delay before retry", retry_delay_sub: "Seconds to wait before redialing",
    ring_timeout: "Ring timeout", ring_timeout_sub: "Seconds to wait for answer before hanging up",
    unit_times: "times", unit_seconds: "seconds",
    setup_title: "Alert setup",
    setup_sub: "Define who can send alerts in, and who gets called when they do",
    setup_tab_devices: "Devices & keys", setup_tab_events: "Event types", setup_tab_contacts: "Contact groups",
    setup_flow_title: "Setup order",
    setup_step_group: "Contact group", setup_step_group_hint: "Numbers to call, in order",
    setup_step_event: "Event type", setup_step_event_hint: "What is said + which group to call",
    setup_step_device: "Device & key", setup_step_device_hint: "Who may send, and what they may send",
    setup_count: (n: number) => `${n} item${n === 1 ? "" : "s"}`,
    setup_none: "none yet",
    et_group_label: "Default contact group (optional)",
    et_group_optional_none: "— none (set per device) —",
    et_group_optional_hint: "Usually leave empty — the group actually called is set per device. This is only used when testing from the dashboard.",
    dev_call_group: "calls group", dev_call_group_none: "— pick a group —",
    dev_call_group_missing: "no group picked yet",
    dev_key_full: "This device's full key",
    dev_key_locked: "This device predates key storage — only the prefix is visible. Create a new device if you need the full key.",
    dev_api_title: "How this device sends alerts",
    dev_api_sub: "Everything the board needs is here — no need to open the API guide",
    dev_api_key_note: "This command already contains the real key — paste it straight into the firmware. Never share it or commit it to a public repo.",
    dev_api_no_event: "Pick the events this device may send first, and the examples will follow",
    dev_api_ok: "Success response", dev_api_err: "Error response",
    dev_api_status: "Common status codes",
    dev_api_status_401: "Wrong key, or the device was deleted",
    dev_api_status_403: "Key is valid but this event is not allowed — tick it on the left",
    dev_api_status_404: "No event type with that code",
    dev_api_status_422: "Missing X-API-Key header, or malformed JSON",
    setup_ready: "Ready to receive alerts",
    setup_blocked: (what: string) => `Not usable yet — needs ${what} first`,
    cfg_saving: "Saving…", cfg_saved: "Saved", cfg_save_failed: "Could not save",
    gsm_restart: "Restart module", gsm_restarting: "Restarting…",
    gsm_restart_confirm_title: "Restart the 4G module?",
    gsm_restart_confirm_body: "The radio is switched off and on, then re-registers on the network. Takes about 10-30 seconds, during which no calls can be placed. Queued jobs are dialed once it is back, and any call in progress is always allowed to finish first.",
    gsm_restart_hint: "Use when signal is lost, the network cannot be found, or the module stops responding",
    gsm_restart_ok: "Module restarted and back on the network",
    gsm_restart_failed: "Restarted but not registered yet — check the SIM and antenna",
    gsm_restart_sent: "Command sent, waiting for the module to come back",
    retry_count_help: "If the first contact does not answer, how many more times to redial the same number before moving on to the next contact in the group.",
    retry_count_example: (n: number) =>
      n === 0
        ? "0 = never redial — move to the next contact immediately (best when speed matters most)"
        : `${n} → the first number is dialed ${n + 1} times total (first attempt + ${n} retries) before contact 2 is tried`,
    retry_delay_help: "How long to wait before redialing. The system is not idle during this time — it picks up other queued jobs meanwhile.",
    retry_delay_example: (n: number) => `${n} → no answer at 10:00:00, redial happens at 10:00:${String(n % 60).padStart(2, "0")}`,
    ring_timeout_help: "How long to let the phone ring before giving up. Too short and nobody can pick up; too long and the queue moves slowly.",
    ring_timeout_example: (n: number) => `${n} → rings for ${n}s with no answer, then hangs up and counts as one "no answer"`,
    call_budget_title: "Worst case per contact",
    call_budget: (sec: number, tries: number) =>
      `${sec}s (~${Math.ceil(sec / 60)} min) per contact — ${tries} attempts before moving to the next one`,
    save_btn: "Save settings", save_ok: "Settings saved successfully",
    contacts_title: "Notification groups", contacts_sub: "Manage phone numbers by escalation order",
    add_group: "Add group", new_group: "New group", new_group_ph: "e.g. database_team", create: "Create",
    no_phones: "No phone numbers yet — add one below", phone_ph: "+66812345678",
    phones_count: (n: number) => `${n} number${n !== 1 ? "s" : ""}`,
    group_delete_confirm: "Delete this group? All its phone numbers will be removed too.",
    api_title: "API Guide", api_sub: "Reference documentation for external integrations",
    api_key_section: "API key", api_key_warn: "Never expose this API key publicly. Always pass it via an environment variable or secret manager.",
    copy: "Copy", copied: "Copied",
    copy_failed: "Copy failed — select the text and copy it manually",
    endpoint_title: "POST /notify",
    endpoint_desc: "Queue a call alert by event type code. The system dials numbers in the escalation order of the linked group.",
    curl_title: "Example curl request", resp_title: "Example response",
    manage_keys_hint: "Manage real API keys on the",
    api_quickstart_title: "Get started in 3 steps",
    qs_step1_title: "Create an event type", qs_step1_desc: "Define a code, message, and recipient group",
    qs_step2_title: "Generate an API key", qs_step2_desc: "So external systems can authenticate",
    qs_step3_title: "Call the endpoint", qs_step3_desc: "Send POST /notify with your API key",
    request_body_title: "Request body", response_title: "Response",
    resp_field_job_id_desc: "The queued job's ID — use it to check status later",
    resp_field_status_desc: "The job's initial status (usually queued)",
    resp_field_message_desc: "Confirmation message for display",
    code_examples_title: "Code examples", error_resp_title: "Example error response",
    base_url_note: "Replace https://your-pi.local with your device's actual network address.",
    base_url_label: "Base URL", request_body_json_label: "Request body (JSON)",
    col_parameter: "Parameter", col_required: "Required", col_type: "Type", col_description: "Description",
    status_codes_title: "HTTP status codes",
    status_200_desc: "Request succeeded — the job has been queued",
    status_400_desc: "The request is well-formed but can't be processed, e.g. the event type is disabled or the template needs a variable you didn't send",
    status_401_desc: "The API key is invalid or has been revoked (omitting the X-API-Key header entirely returns 422 instead)",
    status_404_desc: "No event type matches the given code",
    status_422_desc: "The request body is malformed, e.g. event_type_code is missing or has the wrong type (checked automatically)",
    status_500_desc: "An internal error occurred — please try again",
    badge_success: "Success", badge_failed: "Failed", badge_retrying: "Retrying",
    badge_calling: "Calling", badge_queued: "Queued",
    badge_no_answer: "No answer", badge_busy: "Busy", badge_escalated: "Next contact",
    pi_label: "Raspberry Pi", tower_label: "4G Signal", phone_label: "Call alert",
    required: "required", optional: "optional",
    loading: "Loading...", error_generic: "Something went wrong, please try again", retry_action: "Retry",
    cancel: "Cancel", save: "Save", saving: "Saving...", delete: "Delete", edit: "Edit", close: "Close",
    confirm: "Confirm", yes_delete: "Yes, delete",
    event_types_title: "Event Types", event_types_sub: "Define event codes, message templates, and recipient groups for external systems",
    add_event_type: "Add event type", new_event_type: "New event type", edit_event_type: "Edit event type",
    code_label: "Code", code_ph: "e.g. power_outage", code_hint: "Lowercase letters, numbers and _ only. Cannot be changed later.",
    display_name_label: "Display name", display_name_ph: "e.g. Power outage",
    message_template_label: "Message template", message_template_ph: "e.g. Power outage at {location} at {value}",
    message_template_hint: "Use {variable_name} placeholders to fill in values when a real notification is sent",
    group_label: "Recipient group", active_label: "Active",
    col_code: "Code", col_name: "Display name", col_active: "Status", col_actions: "Actions",
    send_test: "Send test", test_dialog_title: "Send a test notification",
    test_variables_label: "Variables", test_variables_hint: "One key=value per line",
    test_message_override_label: "Message (optional — leave blank to use the template)",
    send: "Send", sending: "Sending...", test_sent_ok: (id: number) => `Test notification queued — job #${id}`,
    delete_confirm_title: "Confirm delete", event_type_delete_confirm: "Delete this event type?",
    code_exists_error: "This code already exists", no_event_types: "No event types yet",
    api_keys_title: "API Keys", api_keys_sub: "Manage keys used by external systems calling /notify",
    add_key: "Create new key", new_key_name_label: "Key name", new_key_name_ph: "e.g. Monitoring board",
    key_created_title: "API key created", key_created_warning: "Copy this key now — it will never be shown again.",
    key_prefix_label: "Key", last_used_label: "Last used", created_label: "Created", revoked_label: "Revoked",
    status_active: "Active", status_revoked: "Revoked", never: "Never used",
    revoke: "Delete", revoke_confirm_title: "Confirm delete", revoke_confirm_body: "Delete this device? Its key stops working immediately and cannot be recovered (past call history is kept).",
    no_api_keys: "No API keys yet",
    filter_date_from: "From date", filter_date_to: "To date",
    toast_created: "Created successfully", toast_updated: "Updated successfully", toast_deleted: "Deleted successfully",

    // ─── Devices (1 key = 1 device) ───
    devices_title: "Devices & keys",
    devices_sub: "One key per device — flash it once, change everything else from here",
    devices_summary: (n: number, active: number) => `${n} devices · ${active} active`,
    add_device: "Add device",
    device_name_label: "Device name",
    device_name_ph: "e.g. Node Building A Floor 3",
    device_name_hint: "Spoken in the call in place of {device} — editable later, no reflash needed",
    device_configure: "Configure",
    device_test_call: "Test call",
    device_remove: "Delete device",
    device_remove_confirm: "Click again to confirm",
    device_online: "Recently reported",
    device_never_used: "Never reported",
    devices_empty_title: "No devices yet",
    devices_empty_body: "Create the first key so a board can send alerts in",

    allowed_events_label: "Allowed alerts",
    allowed_events_none: "No permissions yet — anything this device sends will be rejected (403)",
    allowed_events_pick: "Pick the event types this device may trigger",
    allowed_events_empty_hint: "No event types exist yet — create one on the Event Types page first",

    key_once_title: "This key is shown once",
    key_once_body: "Copy it into the firmware now — once you close this you cannot see it again (only a hash is stored)",
    key_no_copy_hint: "Only the key prefix is visible because the server stores a hash, not the full key",
    save_and_configure: "Save and configure",
    save_only: "Save for now",
    done: "Done",

    device_config_title: "Device settings",
    what_will_happen: "What happens when this device reports",
    what_will_happen_empty: "No alert permissions granted yet",
    payload_title: "Payload the device must send",
    shared_config_note: "Recipients and message text are shared per event type — editing them affects every device using that type",
    goto_event_types: "Edit event type",
    goto_contacts: "Edit groups",
    // ─── Signal Flow Monitor ───
    flow_title: "Signal Flow Monitor",
    flow_node_api: "API Gateway",
    flow_node_pi: "Raspberry Pi",
    flow_node_antenna: "4G Tower",
    flow_node_phone: "Phone",
    flow_step_preparing: "Generating speech",
    flow_step_uploading: "Uploading audio to module",
    flow_step_dialing: "Dialing, waiting for answer",
    flow_step_playing: "Answered, playing message",
    flow_step_waiting_retry: "Call failed, waiting to retry",
    flow_result_rejected: "Call rejected — retrying soon",
    flow_result_no_answer: "No answer — retrying soon",
    flow_result_busy: "Line busy — retrying soon",
    flow_cap_received: "Request received",
    flow_cap_tts: "Generating speech",
    flow_cap_upload: "Uploading to module",
    flow_cap_dialing: "Connecting call",
    flow_cap_playing: "Playing message",
    flow_cap_retry: "Waiting to retry",
    flow_state_idle: "Idle",
    flow_state_calling: "Dialing",
    flow_state_ringing: "Ringing / waiting retry",
    flow_state_success: "Answered",
    flow_state_failed: "Failed",
    flow_gsm_offline: "Module not connected",
    flow_source: (n: number) => `${n} in queue`,
    flow_step_note: "Per-step timing (payload received → key checked → dial → answered → audio finished) needs a GET /history/{job_id} endpoint. This currently derives from the latest job status only.",
    flow_layout_style: "Layout style",
    module_ready: "Online", module_not_ready: "Offline", sign_out_short: "Sign out",
    dash_last_update: (t: string) => `Updated ${t}`,
    dash_refresh_every: (s: number) => `Auto-refresh every ${s}s`,
    pipe_title: "Pipeline now", pipe_flow: "payload → key check → queue → call → result",
    pipe_queued: "Queued", pipe_calling: "Dialing", pipe_retry: "Awaiting retry", pipe_done: "Finished today",
    pipe_queued_sub: "waiting for worker", pipe_calling_sub: "on the line", pipe_retry_sub: "next round", pipe_done_sub: "all outcomes",
    pipe_none: "empty",
    flow_signal_step: "SIGNAL STEP",
    flow_auto: "Auto", flow_demo_mode: "demo", flow_incoming_requests: "INCOMING REQUESTS",
    flow_badge_working: "working", flow_badge_queued: (n: number) => `${n} queued`,
    flow_req: (n: number) => `${n} req`,
    flow_demo_note: "Demo mode — the view is forced to this state and does not reflect the real system.",
    flow_time_unknown: "No per-step timing yet",
    flow_legend_done: "Done", flow_legend_active: "In progress", flow_legend_ringing: "Ringing",
    flow_legend_failed: "Failed", flow_legend_pending: "Not yet",
    flow_open_settings: "Go to call settings",
    flow_steps: ["Request in", "Key check", "Speech built", "Ready to send",
      "Module linked", "Audio upload", "Dialing", "Answered"],
    flow_step_aria: (n: number, name: string) => `Step ${n} of 8 · ${name}`,
    flow_all_steps_done: "All 8 steps complete",
    api_base_label: "base",
    api_notes_title: "Good to know",
    api_note_1: "The device name set in the dashboard is spoken in place of {device} — the board never sends its own name",
    api_note_2: "Recipients and message text can be changed later without touching the firmware",
    api_note_3: "On a 403, grant that device permission for the event type on the Devices page",
    api_note_4: "The key is shown once at creation. If lost, delete the device and create a new one (requires reflashing)",
    sys_section_hw: "Hardware", sys_section_call: "Call settings", sys_section_app: "App & account",


    // ─── System & hardware ───
    sys_title: "System & hardware",
    sys_meta: "4G module · Raspberry Pi · call settings · account",
    sys_module_4g: "4G module",
    sys_module_offline: "Not connected",
    sys_module_port: "Port",
    sys_module_updated: "Last updated",
    sys_pi_title: "Raspberry Pi",
    sys_call_config: "Call settings",
    sys_call_config_note: "Saved automatically on every change — the worker picks up new values within seconds, no restart needed",
    sys_runtime: "Runtime",
    sys_theme_label: "Page theme",
    sys_theme_to_light: "Switch to light",
    sys_theme_to_dark: "Switch to dark",
    sys_missing_title: "Not in the backend yet",
    sys_missing_body: "SIM credit · module restart · voice gender+speed · change password from the web · sign out everywhere — the design allows for these but no endpoint backs them yet, so they are not shown as dead controls",

    // ─── Call log ───
    log_filter_all: "All",
    log_filter_ok: "Answered",
    log_filter_no_answer: "No answer",
    log_filter_failed: "Failed",
    log_export_csv: "Export CSV",
    log_export_note: "Exports the current page only",
    log_date_from: "From", log_date_to: "To",
    log_date_today: "Today", log_date_7d: "7 days", log_date_30d: "30 days",
    log_date_all: "All time", log_date_custom: "Custom",
    log_group_status: "Result", log_group_range: "Date range",
    log_col_device: "Device",
    log_col_event: "Event",
    log_empty: "No records match the selected filter",
    log_range: (from: number, to: number, total: number) => `${from}–${to} / ${total}`,

    // ─── Dashboard ───
    dash_auto_refresh: "Auto-refresh every 5s",
    dash_signal_4g: "4G signal",
    dash_success_fail: "Success / failed",
    dash_tap_row_hint: "Tap a row for details",
    dash_view_all: "View all",
    dash_calls_24h: "Calls over 24h",
    dash_spoken: "Spoken message",
    dash_no_events: "No events yet",
    dash_detail_note: "The full per-step timeline (payload received → key checked → dial → answered → audio finished) needs a GET /history/{job_id} endpoint. This shows what /history returns today.",
    dash_last_attempt: "Last attempt",
    dash_retry_count: "Retries so far",
    dash_contact_index: "Contact index",
    dash_hours_capped: "Counted from the latest 100 records of today",

    retry_summary: (count: number, delay: number) => `No answer → retry ${count} times, ${delay}s apart`,
    escalate_summary: "Still no answer after retries → move to the next number in the group",
  },
} as const;

export type Tr = typeof TR.th;

// ─── App context ──────────────────────────────────────────────────────────────

export interface AppCtx {
  T: Tr;
  dark: boolean;
  toggleDark: () => void;
  lang: Lang;
  toggleLang: () => void;
}

export const Ctx = createContext<AppCtx>(null!);
export const useApp = () => useContext(Ctx);

const LANG_STORAGE_KEY = "gateway_lang";
const DARK_STORAGE_KEY = "gateway_dark";

function getStoredLang(): Lang {
  const stored = localStorage.getItem(LANG_STORAGE_KEY);
  return stored === "en" ? "en" : "th";
}

function getStoredDark(): boolean {
  const stored = localStorage.getItem(DARK_STORAGE_KEY);
  if (stored !== null) return stored === "true";
  return window.matchMedia?.("(prefers-color-scheme: dark)").matches ?? false;
}

export function AppProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(getStoredLang);
  const [dark, setDark] = useState<boolean>(getStoredDark);

  const T = TR[lang] as Tr;
  const toggleDark = () => setDark((d) => !d);
  const toggleLang = () => setLang((l) => (l === "th" ? "en" : "th"));

  useEffect(() => {
    document.documentElement.classList.toggle("dark", dark);
    // ต้องใส่ .light ด้วย ไม่ใช่แค่ถอด .dark — theme.css มี @media (prefers-color-scheme: dark)
    // ที่ยิงใส่ :root:not(.light) ถ้าไม่มีคลาสนี้ เครื่องที่ตั้ง OS เป็น dark ไว้
    // จะถูกบังคับเป็น dark ทับการเลือก light ของผู้ใช้
    document.documentElement.classList.toggle("light", !dark);
    localStorage.setItem(DARK_STORAGE_KEY, String(dark));
  }, [dark]);

  useEffect(() => {
    localStorage.setItem(LANG_STORAGE_KEY, lang);
  }, [lang]);

  const ctx: AppCtx = { T, dark, toggleDark, lang, toggleLang };

  return <Ctx.Provider value={ctx}>{children}</Ctx.Provider>;
}
