import { useState, useEffect, createContext, useContext, type ReactNode } from "react";
import { clockAfter, formatDurationEn, formatDurationTh } from "../lib/duration";
import type { Lang } from "../types";

// ─── Translations ─────────────────────────────────────────────────────────────

export const TR = {
  th: {
    app_name: "4G Gateway", app_version: (v: string) => `เวอร์ชัน ${v}`,
    nav_overview: "ภาพรวม", nav_queue: "คิวการโทร", nav_history: "ประวัติการโทร",
    nav_settings: "การตั้งค่า", nav_contacts: "กลุ่มผู้รับ", nav_api: "คู่มือ", nav_logout: "ออกจากระบบ",
    nav_event_types: "ประเภทเหตุการณ์", nav_api_keys: "API keys",
    tab_overview: "ภาพรวม", tab_queue: "คิว", tab_history: "ประวัติ", tab_settings: "ตั้งค่า", tab_contacts: "กลุ่ม",
    tab_event_types: "เหตุการณ์", tab_api_keys: "API keys",
    login_sub: "แจ้งเตือน IoT ด้วยการโทรผ่าน 4G", login_username: "ชื่อผู้ใช้", login_password: "รหัสผ่าน",
    login_submit: "เข้าสู่ระบบ", login_error: "กรุณากรอกข้อมูลให้ครบ", login_invalid: "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง",
    login_welcome: "ยินดีต้อนรับกลับมา",
    login_username_ph: "กรอกชื่อผู้ใช้", login_password_ph: "กรอกรหัสผ่าน",
    login_map_alt: "แผนที่โลกแสดงเครือข่ายที่เชื่อมถึงกัน (ภาพประกอบ)",
    login_panel_connected: "เชื่อมต่อสำเร็จ", login_panel_sent: "ส่งสัญญาณแล้ว", login_panel_dialing: "กำลังโทร…", login_panel_signal: "สัญญาณดี",
    login_flow_device: "อุปกรณ์ IoT", login_flow_gateway: "เกตเวย์ 4G", login_flow_people: "โทรหาผู้รับ",
    overview_title: "ภาพรวมระบบ", overview_sub: "สถานะระบบและสรุปการโทรวันนี้",
    stat_calls: "โทรออกวันนี้", stat_calls_sub: "ตั้งแต่เที่ยงคืน",
    stat_rate: "อัตราสำเร็จ", stat_rate_sub: (ok: number, total: number) => `${ok} จาก ${total} สาย`,
    stat_rate_none: "ยังไม่มีสายวันนี้",
    stat_queue: "รอในคิว", stat_queue_sub: "งาน active",
    recent_title: "กิจกรรมล่าสุด", recent_sub: "5 รายการล่าสุด", realtime: "ข้อมูลเรียลไทม์", sample_data: "ข้อมูลตัวอย่าง",
    outcome_title: "ผลการโทรวันนี้", outcome_empty: "ยังไม่มีสายวันนี้",
    outcome_sub: (n: number) => `จากทั้งหมด ${n} สาย`,
    system_info_title: "System info", system_info_worker: "Call worker",
    system_info_worker_running: "กำลังทำงาน", system_info_worker_stopped: "ยังไม่เริ่มทำงาน",
    system_info_uptime: "Uptime", system_info_gsm: "GSM module", system_info_gsm_port: "พอร์ต",
    system_info_db_size: "ขนาดฐานข้อมูล", system_info_version: "เวอร์ชัน",
    device_pi_label: "Raspberry Pi", device_gsm_label: "GSM Module",
    device_view_detail: "แตะเพื่อดูรายละเอียด",
    gsm_detail_title: "รายละเอียด GSM Module", gsm_mode_label: "โหมดเครือข่าย", gsm_operator_label: "เครือข่าย",
    gsm_signal_label: "ความแรงสัญญาณ", gsm_signal_unknown: "ไม่ทราบ", gsm_no_operator: "ไม่มีสัญญาณ",
    gsm_signal_excellent: "ดีมาก", gsm_signal_good: "ดี", gsm_signal_fair: "พอใช้", gsm_signal_poor: "อ่อน",
    dash_signal_fix: "ดูหน้าระบบ",
    gsm_status_ok: "ออนไลน์", gsm_status_error: "สัญญาณขัดข้อง",
    pi_detail_title: "รายละเอียด Raspberry Pi", pi_cpu_label: "การใช้งาน CPU", pi_ram_label: "การใช้งาน RAM",
    pi_temp_label: "อุณหภูมิ CPU", pi_temp_unavailable: "อ่านค่าไม่ได้บนเครื่องนี้",
    widget_title: "สถานะการโทรแจ้งเตือน",
    widget_idle: "รอการเชื่อมต่อ", widget_active: "กำลังโทร...", widget_success: "โทรสำเร็จ", widget_failed: "ไม่รับสาย — กำลัง retry",
    queue_title: "คิวการโทร", queue_sub: "งานที่รอดำเนินการและกำลังทำงาน", queue_live: "Live",
    queue_empty: "คิวว่างเปล่า", queue_empty_sub: "ไม่มีงานรอดำเนินการในขณะนี้",
    queue_legend_title: "ความหมายของสถานะ",
    col_id: "Job ID", col_group: "กลุ่ม", col_phone: "เบอร์โทร", col_status: "สถานะ",
    col_retry: "retry", col_created: "สร้างเมื่อ", col_datetime: "วันที่-เวลา", col_note: "หมายเหตุ",
    history_title: "ประวัติการโทร", history_records: (n: number) => `รายการโทรทั้งหมด ${n} รายการ`,
    search_ph: "ค้นหาข้อความหรือ job ID…", search_short: "ค้นหา…",
    all_status: "สถานะทั้งหมด", all_groups: "กลุ่มทั้งหมด", clear: "ล้าง",
    filters_btn: "ตัวกรอง", filters_title: "ตัวกรอง", filters_apply: "ใช้ตัวกรอง", filters_reset: "ล้างตัวกรอง",
    no_data: "ไม่พบข้อมูล", page_of: (p: number, t: number) => `หน้า ${p} จาก ${t}`,
    prev: "← ก่อนหน้า", next: "ถัดไป →",
    filter_status: "สถานะ", filter_group: "กลุ่มผู้รับ",
    settings_title: "การตั้งค่า", settings_sub: "พฤติกรรมการโทรและ fallback",
    retry_section: "พฤติกรรม retry", retry_section_sub: "กำหนดจำนวนครั้งและระยะเวลาในการโทรซ้ำ",
    answer_delay: "เว้นช่วงก่อนเริ่มพูด",
    answer_delay_help: "รับสายแล้วรอกี่วินาทีค่อยเริ่มพูด คนรับต้องยกหูขึ้นแนบหูก่อน ถ้าพูดทันทีประโยคแรกจะหายไป",
    answer_delay_example: (n: number) =>
      n === 0 ? "ตั้ง 0 = พูดทันทีที่กดรับ เสี่ยงประโยคแรกหาย" : `ตั้ง ${n} วินาที → กดรับตอน 10:00:00 จะเริ่มพูดตอน 10:00:${String(n).padStart(2, "0")}`,
    repeat_count: "พูดซ้ำกี่รอบ",
    repeat_count_help: "พูดข้อความเดิมซ้ำกี่รอบใน 1 สาย ฟังรอบเดียวมักจับใจความไม่ครบ โดยเฉพาะตอนเพิ่งตื่นหรืออยู่ในที่เสียงดัง",
    repeat_count_example: (n: number) =>
      n === 1 ? "ตั้ง 1 = พูดครั้งเดียวแล้ววางสาย" : `ตั้ง ${n} = พูดซ้ำ ${n} รอบ เว้นรอบละ 1.5 วินาที · ปลายสายวางก่อนก็หยุดเอง`,
    retry_count: "จำนวนครั้งที่โทรซ้ำ", retry_count_sub: "โทรซ้ำสูงสุดกี่ครั้งก่อนจะถือว่าล้มเหลว",
    retry_delay: "เวลารอก่อนโทรซ้ำ", retry_delay_sub: "ระยะเวลาที่รอก่อนโทรซ้ำ",
    ring_timeout: "เวลารอให้รับสาย", ring_timeout_sub: "ระยะเวลาที่รอสายก่อนตัดว่าไม่รับ",
    unit_times: "ครั้ง", unit_seconds: "วินาที", unit_minutes: "นาที",
    sys_theme_light: "กลางวัน", sys_theme_dark: "กลางคืน",
    ov_success: "สำเร็จ", ov_failed: "ล้มเหลว", ov_done_today: "จบแล้ววันนี้",
    ov_live_queue: "คิวแบบเรียลไทม์", ov_jobs: "งาน",
    ov_queue_empty: "คิวว่าง — ระบบพร้อมรับงาน",
    ov_col_name_phone: "ชื่อ / เบอร์", ov_col_time: "เวลา",
    ov_health: "สุขภาพระบบ",
    ov_health_ok: "ปกติ", ov_health_high: "สูง", ov_health_critical: "วิกฤต",
    ov_axis_max: (n: number) => `สูงสุด ${n} สาย/ชม.`,
    ov_health_scale_ok: (hi: number) => `ปกติ ต่ำกว่า ${hi}%`,
    ov_health_scale_high: (lo: number, hi: number) => `สูง ${lo}–${hi}%`,
    ov_health_scale_critical: (lo: number) => `วิกฤต ตั้งแต่ ${lo}% ขึ้นไป`,
    ov_hour_calls: (hour: string, n: number) => `${hour} — ${n} สาย`,
    ov_temp: "อุณหภูมิ", ov_peak: "ช่วงพีค",
    ov_peak_at: (h: string, n: number) => `${h} · ${n} สาย`,
    ov_no_peak: "ยังไม่มีสายวันนี้",
    duration_range: (lo: number, hi: number) =>
      `ตั้งได้ ${formatDurationTh(lo)} ถึง ${formatDurationTh(hi)}`,
    count_range: (lo: number, hi: number, unit: string) => `ตั้งได้ ${lo} ถึง ${hi} ${unit}`,
    cfg_example_label: "ตัวอย่าง",
    setup_title: "ตั้งค่าการแจ้งเตือน",
    setup_sub: "กลุ่มผู้รับ · ประเภทเหตุการณ์ · อุปกรณ์ & key",
    setup_tab_devices: "อุปกรณ์ & key", setup_tab_events: "ประเภทเหตุการณ์", setup_tab_contacts: "กลุ่มผู้รับ",
    et_used_by: "ใช้โดยอุปกรณ์",
    et_used_by_count: (n: number) => `${n} อุปกรณ์`,
    et_used_by_none: "— ยังไม่มีอุปกรณ์ใช้ —",
    event_type_delete_in_use: (n: number) =>
      `ตอนนี้มีอุปกรณ์ ${n} ตัวใช้เหตุการณ์นี้อยู่ ลบแล้วอุปกรณ์เหล่านั้นจะยิงเหตุการณ์นี้ไม่ได้อีก (ประวัติการโทรเดิมยังอยู่ครบ)`,
    dev_call_group_none: "— เลือกกลุ่ม —",
    /* ── หน้าอุปกรณ์แบบใหม่: รายการซ้าย + ตั้งค่าขวา จอเดียวจบ ────────── */
    dv_search_ph: "ค้นหาอุปกรณ์ ชื่อ หรือ key",
    dv_count_all: "อุปกรณ์ {n} ตัว",
    dv_count_found: "พบ {n} จาก {all} ตัว",
    dv_pill_ready: "พร้อม",
    dv_pill_off: "ปิดอยู่",
    dv_pill_noevent: "ยังไม่เปิดเหตุการณ์",
    dv_pill_notarget: "ไม่มีคนรับสาย",
    dv_active_on: "เปิดใช้งาน",
    dv_active_off: "ปิดอยู่",
    dv_off_banner: "อุปกรณ์นี้ถูกปิดอยู่ — ยิงเข้ามาก็จะไม่โทรออก การตั้งค่าด้านล่างยังเก็บไว้ให้ครบ",
    dv_events_on: "เหตุการณ์ที่เปิดใช้งาน",
    dv_add_event: "เพิ่มเหตุการณ์",
    dv_add_event_title: "เพิ่มเหตุการณ์ให้อุปกรณ์นี้",
    dv_add_event_ph: "— เลือกเหตุการณ์ —",
    dv_add_event_hint: "เพิ่มแล้วยังต้องตั้งต่อว่าใครรับสาย ไม่งั้นยิงเข้ามาจะถูกปฏิเสธ",
    dv_add_event_none: "อุปกรณ์นี้เปิดครบทุกเหตุการณ์ที่มีในระบบแล้ว",
    dv_no_events_yet: "ยังไม่ได้เปิดเหตุการณ์ไหนเลย — ยิงอะไรเข้ามาก็จะถูกปฏิเสธทั้งหมด",
    dv_recip_group: "กลุ่ม:",
    dv_recip_custom: "เจาะเบอร์ {n} คน",
    dv_recip_none: "ยังไม่ได้ตั้งผู้รับสาย",
    dv_configure: "ตั้งค่า",
    dv_key_show: "แสดง", dv_key_hide: "ซ่อน",
    dv_mode_group_desc: "ไล่โทรตามลำดับในกลุ่ม คนแรกไม่รับก็โทรคนถัดไปเอง",
    dv_mode_custom_desc: "เจาะเป็นรายคน ข้ามกลุ่มได้ เลขที่ขึ้นคือลำดับที่จะไล่โทร",
    dv_pick_group: "เลือกกลุ่มที่จะให้โทร",
    dv_search_recip_ph: "ค้นหากลุ่ม ชื่อ หรือเบอร์",
    dv_search_none: "ไม่พบรายการที่ตรงกับคำค้น",
    dv_col_people: "สมาชิก", dv_col_person: "ชื่อผู้รับสาย", dv_col_in_group: "อยู่กลุ่ม",
    dv_col_order: "ลำดับ",
    dv_no_groups: "ยังไม่มีกลุ่มผู้รับในระบบ — ไปสร้างที่แท็บกลุ่มผู้รับก่อน",
    dv_remove_event_confirm: "เอาเหตุการณ์นี้ออกจากอุปกรณ์? ผู้รับสายที่ตั้งไว้ของคู่นี้จะหายไปด้วย และอุปกรณ์จะยิงเหตุการณ์นี้ไม่ได้อีก",
    dv_delete_device_confirm: "ลบอุปกรณ์นี้? key จะใช้ไม่ได้ทันทีและเอากลับไม่ได้ — ประวัติการโทรเดิมยังอยู่ครบ",
    dv_no_events: "ยังไม่มีประเภทเหตุการณ์ในระบบ — ไปสร้างที่แท็บประเภทเหตุการณ์ก่อน",
    dv_saving: "กำลังบันทึก…",
    dev_target_mode: "ผู้รับสาย",
    dev_target_group: "ทั้งกลุ่ม",
    dev_target_contacts: "เลือกเบอร์เอง",
    dev_target_missing: "ยังไม่ได้เลือกผู้รับ — ยิงเหตุการณ์นี้เข้ามาจะถูกปฏิเสธ",
    dev_pick_contacts_hint: "ติ๊กเฉพาะคนที่ต้องการ ข้ามกลุ่มได้ ลำดับที่ติ๊กคือลำดับไล่สาย (ปรับได้ด้านล่าง)",
    dev_no_contacts_at_all: "ยังไม่มีเบอร์ในระบบเลย — ไปเพิ่มที่หน้ากลุ่มผู้รับก่อน",
    dev_call_order: "ลำดับการโทร",
    dev_will_call: "โทรหา",
    dev_group_empty: "ยังไม่มีเบอร์ในกลุ่มนี้",
    move_up: "เลื่อนขึ้น", move_down: "เลื่อนลง",
    dev_key_full: "key เต็มของอุปกรณ์นี้",
    dev_key_locked: "อุปกรณ์นี้สร้างก่อนระบบเก็บ key ไว้ให้ดูซ้ำได้ — เห็นได้แค่ตัวหน้า ถ้าต้องใช้ key เต็มต้องสร้างอุปกรณ์ใหม่",
    dev_api_title: "วิธียิงเข้ามาจากอุปกรณ์นี้",
    dev_api_sub: "ทุกอย่างที่บอร์ดต้องใช้ อยู่ครบในนี้แล้ว ไม่ต้องเปิดหน้า API guide",
    dev_api_key_note: "คำสั่งนี้มี key จริงอยู่แล้ว ก็อปไปวางใน firmware ได้เลย — อย่าแชร์ให้คนอื่นหรือ commit ขึ้น repo สาธารณะ",
    dev_api_no_event: "เลือกเหตุการณ์ที่อุปกรณ์นี้ยิงได้ก่อน แล้วตัวอย่างจะเปลี่ยนตาม",
    dev_api_ok: "ตอบกลับเมื่อสำเร็จ", dev_api_err: "ตอบกลับเมื่อผิดพลาด",
    dev_api_status: "รหัสที่เจอบ่อย",
    dev_api_status_400: "ยังไม่ได้เลือกผู้รับให้เหตุการณ์นี้ หรือกลุ่มที่เลือกไว้ไม่มีเบอร์เลย",
    dev_api_status_401: "key ผิด หรืออุปกรณ์ถูกลบไปแล้ว",
    dev_api_status_403: "key ถูก แต่ยังไม่ได้ให้สิทธิ์ยิงเหตุการณ์นี้ — ติ๊กเพิ่มด้านซ้าย",
    dev_api_status_404: "ไม่มีรหัสเหตุการณ์นี้ในระบบ",
    dev_api_status_422: "ไม่ได้ส่ง header X-API-Key หรือรูปแบบ JSON ผิด",
    cfg_saving: "กำลังบันทึก…", cfg_saved: "บันทึกแล้ว", cfg_save_failed: "บันทึกไม่สำเร็จ",
    gsm_restart: "รีสตาร์ทโมดูล", gsm_restarting: "กำลังรีสตาร์ท…",
    gsm_restart_confirm_title: "รีสตาร์ทโมดูล 4G?",
    gsm_restart_confirm_body: "โมดูลจะปิด-เปิดคลื่นวิทยุแล้วหาเครือข่ายใหม่ ใช้เวลาราว 10-30 วินาที ระหว่างนี้โทรออกไม่ได้ · งานที่รอในคิวจะถูกโทรต่อให้เองหลังเสร็จ · ระบบจะไม่ตัดสายที่กำลังคุยอยู่ (รอจนสายจบก่อนเสมอ)",
    gsm_restart_hint: "ใช้เมื่อสัญญาณหาย หาเครือข่ายไม่เจอ หรือโมดูลไม่ตอบสนอง",
    gsm_restart_ok: "รีสตาร์ทโมดูลสำเร็จ กลับเข้าเครือข่ายแล้ว",
    gsm_restart_failed: "รีสตาร์ทแล้วแต่ยังไม่กลับเข้าเครือข่าย — ลองเช็คซิม/สายอากาศ",
    gsm_restart_sent: "ส่งคำสั่งแล้ว รอโมดูลกลับมาสักครู่",
    retry_count_help: "ถ้าเบอร์แรกไม่รับ จะโทรซ้ำเบอร์เดิมอีกกี่ครั้ง ครบแล้วจึงข้ามไปเบอร์ถัดไปในกลุ่ม",
    retry_count_example: (n: number) =>
      n === 0
        ? "ตั้ง 0 = ไม่โทรซ้ำเลย ไม่รับปุ๊บข้ามไปเบอร์ถัดไปทันที (เหมาะกับเหตุด่วนที่ต้องหาคนรับให้เร็วที่สุด)"
        : `ตั้ง ${n} → โทรเบอร์แรกทั้งหมด ${n + 1} ครั้ง (ครั้งแรก + ซ้ำอีก ${n}) ถ้ายังไม่รับจึงไปเบอร์ที่ 2`,
    retry_delay_help: "รอนานแค่ไหนก่อนโทรซ้ำ ระหว่างรอ ระบบไม่ได้อยู่เฉยๆ — เอาเวลาไปโทรงานอื่นในคิวต่อได้เลย",
    retry_delay_example: (n: number) =>
      `ตั้ง ${formatDurationTh(n)} → ไม่รับตอน 10:00:00 จะโทรซ้ำอีกทีตอน ${clockAfter(n)}`,
    ring_timeout_help: "ปล่อยให้ปลายทางดังนานแค่ไหนก่อนตัดว่าไม่รับ สั้นไปคนหยิบไม่ทัน ยาวไปคิวงานถัดไปเดินช้า",
    ring_timeout_example: (n: number) =>
      `ตั้ง ${formatDurationTh(n)} → ดังครบ ${formatDurationTh(n)} แล้วยังไม่รับ = วางสายเอง นับเป็น "ไม่รับสาย" 1 ครั้ง`,
    call_budget_title: "รวมแล้วเบอร์หนึ่งใช้เวลาสูงสุด",
    call_budget: (sec: number, tries: number) =>
      `${formatDurationTh(sec)} ต่อ 1 เบอร์ — โทร ${tries} ครั้ง แล้วจึงข้ามไปเบอร์ถัดไป`,
    save_btn: "บันทึกการตั้งค่า", save_ok: "บันทึกการตั้งค่าสำเร็จ",
    contacts_title: "กลุ่มผู้รับการแจ้งเตือน",
    contacts_sub: "ไล่โทรจากบนลงล่าง — คนแรกไม่รับ ระบบจะโทรหาคนถัดไปเอง",
    add_group: "เพิ่มกลุ่ม", new_group: "สร้างกลุ่มผู้รับใหม่", new_group_ph: "เช่น ทีมช่างเทคนิค", create: "สร้างกลุ่ม",
    group_name_label: "ชื่อกลุ่ม",
    new_group_hint: "ตั้งชื่อให้คนอ่านแล้วรู้ทันทีว่าเป็นใคร เพราะชื่อนี้จะโผล่ตอนเลือกผู้รับให้อุปกรณ์ เพิ่มเบอร์เข้ากลุ่มได้หลังสร้างเสร็จ",
    contacts_search: "ค้นหาชื่อกลุ่ม ชื่อคน หรือเบอร์โทร",
    contacts_search_none: "ไม่พบกลุ่ม ชื่อ หรือเบอร์ที่ตรงกับคำค้น",
    contacts_search_found: (n: number) => `ตรงกับคำค้น ${n} กลุ่ม`,
    no_phones: "ยังไม่มีเบอร์โทร — เพิ่มด้านล่าง", phone_ph: "0812345678",
    contact_name_ph: "ชื่อผู้รับสาย", edit_group_name: "แก้ชื่อกลุ่ม",
    phones_count: (n: number) => `${n} เบอร์โทร`,
    group_delete_confirm: "ลบกลุ่มนี้? เบอร์โทรทั้งหมดในกลุ่มจะถูกลบด้วย",
    ct_people_count: (n: number) => `${n} คน`,
    ct_col_phones: "จำนวนเบอร์", ct_col_members: "ใครได้รับสายบ้าง",
    ct_edit_group: "แก้ไขกลุ่มผู้รับ",
    ct_members: "สมาชิกในกลุ่ม",
    ct_order_hint: "(ลำดับ = ลำดับที่ระบบจะไล่โทรจริง)",
    ct_add_member: "เพิ่มสมาชิก",
    ct_member_hint: "ต้องกรอกทั้งชื่อและเบอร์ แถวที่กรอกไม่ครบจะไม่ถูกบันทึก — ชื่อคือสิ่งที่ถูกอ่านตอนเกิดเหตุจริง",
    contact_delete_confirm: "เอาเบอร์นี้ออกจากกลุ่ม? คนที่อยู่ลำดับถัดไปจะเลื่อนขึ้นมาถูกโทรแทน",
    api_title: "API guide", api_sub: "เอกสารอ้างอิงสำหรับ integration กับระบบภายนอก",
    guide_title: "คู่มือการใช้งาน", guide_sub: "ตั้งค่ายังไง อ่านผลยังไง และยิงเข้ามาจากอุปกรณ์ยังไง",
    guide_tab_usage: "วิธีใช้งาน", guide_tab_api: "API สำหรับนักพัฒนา",
    api_key_section: "API key", api_key_warn: "อย่าเปิดเผย API key นี้ในที่สาธารณะ ส่ง key ผ่าน environment variable หรือ secret manager เสมอ",
    copy: "คัดลอก", copied: "คัดลอกแล้ว",
    copy_failed: "คัดลอกไม่สำเร็จ — กดค้างที่ข้อความแล้วคัดลอกเองได้",
    endpoint_title: "POST /notify",
    endpoint_desc: "ส่งคำสั่งโทรแจ้งเตือนตามรหัส event type ระบบจะ queue งานและโทรตามลำดับ escalation ของกลุ่มที่ผูกไว้",
    curl_title: "ตัวอย่าง curl request", resp_title: "ตัวอย่าง response",
    manage_keys_hint: "จัดการ API key จริงได้ที่หน้า",
    api_quickstart_title: "เริ่มต้นใช้งานใน 3 ขั้นตอน",
    qs_step1_title: "สร้างประเภทเหตุการณ์", qs_step1_desc: "กำหนดรหัส ข้อความ และกลุ่มผู้รับ",
    qs_step2_title: "สร้าง API key", qs_step2_desc: "สำหรับให้ระบบภายนอกยืนยันตัวตน",
    qs_step3_title: "เรียก endpoint", qs_step3_desc: "ยิง POST /notify พร้อม API key",
    request_body_title: "Request body", response_title: "Response",
    resp_field_job_id_desc: "หมายเลขงานที่เข้าคิว ใช้ตรวจสอบสถานะภายหลังได้",
    resp_field_status_desc: "สถานะเริ่มต้นของงาน (มักเป็น queued)",
    resp_field_message_desc: "ข้อความยืนยันสำหรับแสดงผล",
    code_examples_title: "ตัวอย่างโค้ด", error_resp_title: "ตัวอย่าง response เมื่อเกิดข้อผิดพลาด",
    base_url_note: "แทนที่ https://your-pi.local ด้วยที่อยู่จริงของอุปกรณ์ในเครือข่ายของคุณ",
    base_url_label: "Base URL", request_body_json_label: "Request body (JSON)",
    col_parameter: "พารามิเตอร์", col_required: "จำเป็น", col_type: "ชนิดข้อมูล", col_description: "คำอธิบาย",
    status_codes_title: "HTTP status codes",
    status_200_desc: "Request สำเร็จ งานถูก queue เรียบร้อยแล้ว",
    status_400_desc: "ข้อมูลถูกต้องตามรูปแบบแต่ประมวลผลไม่ได้ เช่น event type ถูกปิดใช้งาน หรือขาดตัวแปรที่ template ต้องการ",
    status_401_desc: "API key ไม่ถูกต้องหรือถูกเพิกถอนแล้ว (ถ้าไม่ได้ส่ง header X-API-Key มาเลยจะได้ 422 แทน)",
    status_404_desc: "ไม่พบ event type ตามรหัสที่ระบุ",
    status_422_desc: "รูปแบบข้อมูลไม่ถูกต้อง เช่น ไม่ได้ส่ง event_type_code มา หรือชนิดข้อมูลผิด (ตรวจสอบอัตโนมัติ)",
    status_500_desc: "ข้อผิดพลาดภายในระบบ กรุณาลองใหม่อีกครั้ง",
    badge_success: "สำเร็จ", badge_failed: "ล้มเหลว", badge_retrying: "กำลัง retry",
    badge_calling: "กำลังโทร", badge_queued: "รอคิว",
    badge_no_answer: "ไม่รับสาย", badge_busy: "สายไม่ว่าง", badge_escalated: "ไล่เบอร์ถัดไป",
    pi_label: "Raspberry Pi", tower_label: "สัญญาณ 4G", phone_label: "โทรแจ้งเตือน",
    required: "required", optional: "optional",
    loading: "กำลังโหลด...", error_generic: "เกิดข้อผิดพลาด กรุณาลองใหม่", retry_action: "ลองอีกครั้ง",
    cancel: "ยกเลิก", save: "บันทึก", saving: "กำลังบันทึก...", delete: "ลบ", edit: "แก้ไข", close: "ปิด",
    confirm: "ยืนยัน", yes_delete: "ใช่ ลบเลย",
    event_types_title: "ประเภทเหตุการณ์",
    event_types_sub: "เรื่องที่แจ้งได้ และประโยคที่จะพูดตอนโทรไปบอก",
    add_event_type: "เพิ่มประเภทเหตุการณ์", new_event_type: "ประเภทเหตุการณ์ใหม่", edit_event_type: "แก้ไขประเภทเหตุการณ์",
    code_label: "รหัส (code)", code_ph: "เช่น power_outage", code_hint: "ตัวพิมพ์เล็ก ตัวเลข และ _ เท่านั้น แก้ไขไม่ได้ภายหลัง",
    display_name_label: "ชื่อที่แสดง", display_name_ph: "เช่น ไฟดับ",
    message_template_label: "ข้อความ template", message_template_ph: "เช่น ไฟดับที่ {location} เวลา {value}",
    message_template_hint: "ใช้ {ชื่อตัวแปร} แทนค่าที่อุปกรณ์จะส่งมาตอนแจ้งเตือนจริง เช่น {temp}",
    et_vars_title: "ตัวแปรในข้อความนี้",
    et_vars_none: "ยังไม่มีตัวแปร — ข้อความจะถูกพูดตามที่พิมพ์ทุกครั้ง ถ้าอยากให้บอกค่าที่วัดได้ ใส่ {temp} ลงไปในข้อความ",
    et_vars_send: "อุปกรณ์ต้องส่งมา",
    et_howto_title: "วิธีการนำไปใช้",
    et_vars_example: "ตัวอย่าง request body",
    et_vars_missing: "ถ้าอุปกรณ์ไม่ส่งค่ามา จะถูกปฏิเสธทันที (400) ไม่เข้าคิว",
    et_limits_title: "ข้อจำกัด",
    et_limit_msg: "ข้อความ ≤ 500 ตัวอักษร",
    et_limit_count: "ตัวแปร ≤ 20 ตัว",
    et_limit_value: "ค่าตัวแปร ≤ 200 ตัวอักษร",
    group_label: "กลุ่มผู้รับ",
    col_code: "รหัส", col_name: "ชื่อที่แสดง", col_active: "สถานะ", col_actions: "จัดการ",
    send_test: "ส่งทดสอบ", test_dialog_title: "ส่งการแจ้งเตือนทดสอบ",
    test_variables_label: "ตัวแปร (variables)", test_variables_hint: "รูปแบบ key=value หนึ่งค่าต่อบรรทัด",
    test_message_override_label: "ข้อความ (ไม่บังคับ — เว้นว่างเพื่อใช้ template)",
    send: "ส่ง", sending: "กำลังส่ง...", test_sent_ok: (id: number) => `ส่งคำขอทดสอบแล้ว — job #${id}`,
    delete_confirm_title: "ยืนยันการลบ", event_type_delete_confirm: "ลบประเภทเหตุการณ์นี้?",
    code_exists_error: "รหัสนี้มีอยู่แล้ว", no_event_types: "ยังไม่มีประเภทเหตุการณ์",
    api_keys_title: "API keys", api_keys_sub: "จัดการ key สำหรับระบบภายนอกที่เรียก /notify",
    add_key: "สร้าง key ใหม่", new_key_name_label: "ชื่อ key", new_key_name_ph: "เช่น Monitoring board",
    key_created_title: "สร้าง API key สำเร็จ", key_created_warning: "คัดลอก key นี้เก็บไว้ตอนนี้ — จะไม่แสดงให้เห็นอีกเป็นครั้งที่สอง",
    key_prefix_label: "Key", last_used_label: "ใช้ล่าสุด", created_label: "สร้างเมื่อ", revoked_label: "เพิกถอนเมื่อ",
    status_active: "ใช้งานอยู่", status_revoked: "ถูกเพิกถอน", never: "ไม่เคยใช้",
    revoke: "ลบ", revoke_confirm_title: "ยืนยันการลบอุปกรณ์", revoke_confirm_body: "ลบอุปกรณ์นี้ออกจากระบบ? key จะใช้ไม่ได้ทันทีและเอากลับไม่ได้ (ประวัติการโทรเดิมยังอยู่)",
    no_api_keys: "ยังไม่มี API key",
    filter_date_from: "ตั้งแต่วันที่", filter_date_to: "ถึงวันที่",
    toast_created: "สร้างสำเร็จ", toast_updated: "แก้ไขสำเร็จ", toast_deleted: "ลบสำเร็จ",

    // ─── หน้าอุปกรณ์ (1 key = 1 อุปกรณ์) ───
    devices_title: "อุปกรณ์ & key",
    devices_sub: "เครื่องที่ส่งเรื่องเข้ามาได้ — แต่ละเครื่องมีรหัสผ่านของตัวเอง ตั้งครั้งเดียวจบ",
    devices_summary: (n: number, active: number) => `${n} อุปกรณ์ · ใช้งานอยู่ ${active}`,
    add_device: "เพิ่มอุปกรณ์",
    device_name_label: "ชื่ออุปกรณ์",
    device_name_ph: "เช่น โหนดตึก A ชั้น 3",
    device_name_hint: "ใช้ระบุที่มาในประวัติการโทรและหน้าคิวงาน — เปลี่ยนทีหลังได้ ไม่ได้ถูกพูดในสาย",
    device_search: "ค้นหาชื่ออุปกรณ์", device_search_none: "ไม่พบอุปกรณ์ที่ตรงกับคำค้น",
    device_configure: "ตั้งค่า",
    device_test_call: "ทดสอบโทร",
    device_remove: "ลบอุปกรณ์",
    device_remove_confirm: "กดอีกครั้งเพื่อยืนยัน",
    device_view: "ดู",
    device_ready: "พร้อมใช้งาน", device_not_ready_events: "ยังไม่ได้ตั้งเรื่อง",
    device_not_ready_recipients: "ไม่มีคนรับสาย", device_off: "ปิดอยู่",
    device_toggle_label: "การใช้งาน",
    device_toggle_on_hint: "เปิดอยู่ — ยิงแจ้งเตือนเข้ามาได้ตามปกติ",
    device_toggle_off_hint: "ปิดอยู่ — ยิงเข้ามาจะถูกปฏิเสธ แต่ key ยังไม่ถูกลบ",
    device_last_alert_label: "แจ้งเตือนล่าสุด",
    device_events_section: "ยิงเรื่องนี้ได้ → โทรหา",
    device_last_alert: (d: string) => `แจ้งเตือนล่าสุด ${d}`,
    device_never_alerted: "ยังไม่เคยแจ้งเตือน",
    device_stat_events: "แจ้งเตือนได้", device_stat_recipients: "โทรหา",
    device_events_value: (n: number) => `${n} เรื่อง`,
    device_recipients_groups: (n: number) => `${n} กลุ่ม`,
    device_recipients_phones: (n: number) => `${n} เบอร์`,
    device_recipients_mixed: (g: number, p: number) => `${g} กลุ่ม + ${p} เบอร์`,
    device_recipients_none: "ยังไม่ได้ตั้ง",
    devices_empty_title: "ยังไม่มีอุปกรณ์",
    devices_empty_body: "สร้าง key แรกเพื่อให้บอร์ดยิงแจ้งเตือนเข้ามาได้",

    allowed_events_label: "การแจ้งเตือนที่ยิงได้",
    allowed_events_none: "ยังไม่ได้ให้สิทธิ์ — อุปกรณ์นี้ยิงอะไรเข้ามาก็จะถูกปฏิเสธ (403)",
    allowed_events_pick: "เลือกประเภทเหตุการณ์ที่อุปกรณ์นี้ยิงได้",
    event_filter: "ค้นหาเหตุการณ์", event_filter_none: "ไม่พบเหตุการณ์ที่ตรงกับคำค้น",
    event_picked_count: (n: number, total: number) => `เลือกแล้ว ${n} จาก ${total}`,
    dev_api_more: "ดูรายละเอียดทั้งหมดในหน้าคู่มือ API",
    allowed_events_empty_hint: "ยังไม่มีประเภทเหตุการณ์ในระบบ — สร้างที่หน้าประเภทเหตุการณ์ก่อน",

    add_device_sub: "สร้างรหัสผ่านประจำอุปกรณ์ 1 ตัว — บอร์ดใช้รหัสนี้ยืนยันตัวเองตอนยิงแจ้งเตือนเข้ามา",
    add_device_step1: "ตั้งชื่อ & เลือกเรื่อง", add_device_step2: "รับรหัส",
    events_selected: (n: number) => `เลือกแล้ว ${n}`,
    events_select_all: "เลือกทั้งหมด", events_clear: "ล้างทั้งหมด",
    key_example_label: "ตัวอย่างที่บอร์ดต้องยิงเข้ามา",
    key_once_title: "key นี้แสดงครั้งเดียว",
    key_once_body: "คัดลอกไปฝังใน firmware ตอนนี้ — ปิดหน้าต่างนี้แล้วจะดูอีกไม่ได้ (ระบบเก็บแค่ค่า hash)",
    key_no_copy_hint: "ดูได้แค่ส่วนหน้าของ key เพราะระบบเก็บแค่ hash ไม่ได้เก็บ key เต็ม",
    save_and_configure: "บันทึกแล้วไปตั้งค่า",
    save_only: "บันทึกไว้ก่อน",
    done: "เสร็จแล้ว",

    device_config_title: "ตั้งค่าอุปกรณ์",
    what_will_happen: "ถ้าอุปกรณ์นี้ยิงเข้ามาจะเกิดอะไร",
    what_will_happen_empty: "ยังไม่ได้ให้สิทธิ์การแจ้งเตือนใดๆ",
    payload_title: "payload ที่อุปกรณ์ต้องส่ง",
    shared_config_note: "เบอร์ผู้รับและข้อความเป็นค่าที่แชร์กันตามประเภทเหตุการณ์ — แก้ที่เดียวมีผลกับทุกอุปกรณ์ที่ใช้ประเภทนั้น",
    goto_event_types: "แก้ประเภทเหตุการณ์",
    goto_contacts: "แก้กลุ่มผู้รับ",
    // ─── Signal Flow Monitor ───
    flow_title: "ติดตามสัญญาณแจ้งเตือน",
    flow_node_api: "API Gateway",
    flow_node_pi: "Raspberry Pi",
    flow_node_antenna: "สัญญาณ 4G",
    flow_node_phone: "โทรศัพท์",
    flow_step_preparing: "กำลังแปลงข้อความเป็นเสียง",
    flow_step_uploading: "กำลังส่งไฟล์เสียงเข้าโมดูล",
    flow_step_dialing: "กำลังโทรออก รอปลายสายรับ",
    flow_step_playing: "รับสายแล้ว กำลังพูดข้อความ",
    flow_step_waiting_retry: "สายไม่สำเร็จ กำลังรอโทรซ้ำ",
    flow_result_rejected: "ปลายสายกดปฏิเสธ — รอโทรซ้ำ",
    flow_result_no_answer: "ไม่มีใครรับสาย — รอโทรซ้ำ",
    flow_result_busy: "สายไม่ว่าง — รอโทรซ้ำ",
    flow_cap_received: "รับข้อมูลแล้ว",
    flow_cap_tts: "กำลังแปลงเสียง",
    flow_cap_upload: "กำลังส่งเข้าโมดูล",
    flow_cap_dialing: "กำลังต่อปลายสาย",
    flow_cap_playing: "กำลังพูดข้อความ",
    flow_cap_retry: "รอโทรซ้ำ",
    flow_cap_idle: "รอคำขอจากอุปกรณ์",
    flow_state_idle: "ว่าง",
    flow_state_calling: "กำลังต่อสาย",
    flow_state_ringing: "กำลังเรียก / รอ retry",
    flow_state_success: "โทรติดแล้ว",
    flow_state_failed: "ล้มเหลว",
    flow_gsm_offline: "โมดูลยังไม่เชื่อมต่อ",
    flow_source: (n: number) => `งานในคิว ${n}`,
    flow_step_note: "จังหวะละเอียดต่อขั้น (รับ payload → ตรวจ key → สั่งโทร → ปลายทางรับ → เล่นเสียงจบ) ต้องมี endpoint GET /history/{job_id} ก่อน ตอนนี้ไล่จากสถานะของงานล่าสุดเท่านั้น",
    flow_layout_style: "รูปแบบการแสดง",
    module_ready: "ออนไลน์", module_not_ready: "ออฟไลน์", sign_out_short: "ออก",
    dash_last_update: (t: string) => `อัปเดตล่าสุด ${t}`,
    dash_refresh_every: (s: number) => `รีเฟรชอัตโนมัติทุก ${s} วิ`,
    pipe_title: "การทำงานตอนนี้", pipe_flow: "payload → ตรวจ key → เข้าคิว → โทร → ผล",
    pipe_queued: "เข้าคิว", pipe_calling: "กำลังโทร", pipe_retry: "รอโทรซ้ำ", pipe_done: "จบแล้ววันนี้",
    pipe_queued_sub: "รอ worker หยิบ", pipe_calling_sub: "กำลังต่อสาย", pipe_retry_sub: "รอรอบถัดไป", pipe_done_sub: "รวมทุกผล",
    pipe_none: "ว่าง",
    flow_signal_step: "SIGNAL STEP",
    flow_auto: "Auto", flow_demo_mode: "สาธิต", flow_incoming_requests: "INCOMING REQUESTS",
    flow_badge_working: "กำลังทำงาน", flow_badge_queued: (n: number) => `รอคิว ${n}`,
    flow_req: (n: number) => `${n} req`,
    flow_demo_note: "โหมดสาธิต — ภาพที่เห็นถูกบังคับให้แสดงสถานะนี้ ไม่ใช่สถานะจริงของระบบ",
    flow_time_unknown: "ยังไม่มีเวลาต่อขั้น",
    flow_legend_done: "ผ่านแล้ว", flow_legend_active: "กำลังทำงาน", flow_legend_ringing: "กำลังเรียกสาย",
    flow_legend_failed: "ไม่สำเร็จ", flow_legend_pending: "ยังไม่ถึง",
    flow_open_settings: "ไปหน้าตั้งค่าการโทร",
    flow_steps: ["รับคำขอ", "ตรวจสิทธิ์", "สร้างเสียงพูด", "เตรียมส่ง",
      "เชื่อมต่อโมดูล", "อัปโหลดเสียง", "กำลังโทร", "ปลายทางรับสาย"],
    flow_step_aria: (n: number, name: string) => `ขั้นตอนที่ ${n} จาก 8 · ${name}`,
    flow_all_steps_done: "ครบทั้ง 8 ขั้นตอน",
    api_base_label: "base",
    api_notes_title: "ข้อควรรู้",
    api_note_1: "ตัวแปรทุกตัวที่เขียนไว้ในข้อความต้องส่งมาใน variables ให้ครบ รวมทั้ง {device} — ขาดตัวใดตัวหนึ่งจะได้ 400",
    api_note_2: "เปลี่ยนเบอร์ผู้รับหรือข้อความทีหลังได้ โดยไม่ต้องแก้ firmware",
    api_note_3: "ถ้าได้ 403 ให้ไปเพิ่มสิทธิ์ event type ให้อุปกรณ์นั้นที่หน้าอุปกรณ์",
    api_note_4: "key แสดงครั้งเดียวตอนสร้าง ถ้าหายต้องเพิกถอนแล้วสร้างใหม่ (ต้องแฟลชบอร์ดใหม่)",
    sys_section_hw: "ฮาร์ดแวร์", sys_section_call: "ค่าการโทร", sys_section_app: "แอปและบัญชี",


    // ─── หน้าระบบ & ฮาร์ดแวร์ ───
    sys_title: "ระบบ & ฮาร์ดแวร์",
    sys_meta: "โมดูล 4G · Raspberry Pi · รันไทม์ · ค่าการโทร",
    sys_module_4g: "โมดูล 4G",
    sys_module_offline: "ยังไม่เชื่อมต่อ",
    sys_module_power: "ไฟโมดูล", sys_module_power_on: "ติด", sys_module_power_off: "ดับ",
    sys_module_port: "พอร์ต",
    sys_module_updated: "อัปเดตล่าสุด",
    sys_pi_title: "Raspberry Pi",
    sys_call_config: "ค่าการโทร",
    sys_call_config_note: "บันทึกอัตโนมัติทุกครั้งที่แก้ · worker เห็นค่าใหม่เองภายในไม่กี่วินาที ไม่ต้อง restart",
    sys_runtime: "รันไทม์",
    sys_theme_label: "ธีมของหน้าเว็บ",
    sys_theme_to_light: "สลับเป็นสว่าง",
    sys_theme_to_dark: "สลับเป็นมืด",

    // ─── หน้าประวัติการโทร (call log) ───
    log_filter_all: "ทั้งหมด",
    log_filter_ok: "โทรสำเร็จ",
    log_filter_no_answer: "ไม่รับสาย",
    log_filter_failed: "ล้มเหลว",
    log_export_csv: "ออกไฟล์ CSV",
    log_export_note: "ออกเฉพาะหน้าที่กำลังดูอยู่",
    log_date_from: "ตั้งแต่", log_date_to: "ถึง",
    log_date_today: "วันนี้", log_date_7d: "7 วัน", log_date_30d: "30 วัน",
    log_date_all: "ทุกช่วงเวลา", log_date_custom: "กำหนดเอง",
    log_date_yesterday: "เมื่อวาน", log_date_this_month: "เดือนนี้",
    log_pick_month: "ทั้งเดือน",
    log_day_calls: (n: number) => `${n} สาย`,
    log_clear_range: "ดูทั้งหมด",
    log_group_status: "ผลการโทร", log_group_range: "ช่วงเวลา", log_group_custom: "ระบุเอง",
    log_col_device: "อุปกรณ์",
    log_col_event: "เหตุการณ์",
    log_empty: "ไม่พบรายการตามเงื่อนไขที่เลือก",
    log_range: (from: number, to: number, total: number) => `${from}–${to} / ${total}`,

    // ─── หน้าภาพรวม (dashboard) ───
    dash_auto_refresh: "รีเฟรชอัตโนมัติทุก 5 วิ",
    dash_signal_4g: "สัญญาณ 4G",
    dash_success_fail: "สำเร็จ / ล้มเหลว",
    dash_tap_row_hint: "แตะแถวเพื่อดูรายละเอียด",
    dash_view_all: "ดูทั้งหมด",
    dash_calls_24h: "การโทร 24 ชั่วโมง",
    dash_spoken: "ข้อความที่พูดในสาย",
    dash_no_events: "ยังไม่มีเหตุการณ์",
    dash_detail_note: "รายละเอียดครบทุกขั้น (รับ payload → ตรวจ key → สั่งโทร → ปลายทางรับ → เล่นเสียงจบ) ต้องมี endpoint GET /history/{job_id} ก่อน ตอนนี้แสดงเท่าที่ /history คืนมาได้",
    dash_last_attempt: "ผลครั้งล่าสุด",
    dash_retry_count: "โทรซ้ำไปแล้ว",
    dash_contact_index: "เบอร์ลำดับที่",
    dash_hours_capped: "นับจากรายการล่าสุด 100 รายการของวันนี้",

    retry_summary: (count: number, delay: number) => `ไม่รับสาย → โทรซ้ำ ${count} ครั้ง ห่างครั้งละ ${delay} วินาที`,
    escalate_summary: "ครบรอบแล้วยังไม่รับ → ไล่โทรเบอร์ถัดไปในกลุ่ม",
  },
  en: {
    app_name: "4G Gateway", app_version: (v: string) => `Version ${v}`,
    nav_overview: "Overview", nav_queue: "Call Queue", nav_history: "Call History",
    nav_settings: "Settings", nav_contacts: "Contacts", nav_api: "Guide", nav_logout: "Log out",
    nav_event_types: "Event Types", nav_api_keys: "API Keys",
    tab_overview: "Overview", tab_queue: "Queue", tab_history: "History", tab_settings: "Settings", tab_contacts: "Contacts",
    tab_event_types: "Events", tab_api_keys: "API Keys",
    login_sub: "IoT Emergency Notification System", login_username: "Username", login_password: "Password",
    login_submit: "Sign in", login_error: "Please fill in all fields", login_invalid: "Invalid username or password",
    login_welcome: "Welcome back",
    login_username_ph: "Enter your username", login_password_ph: "Enter your password",
    login_map_alt: "World map showing a connected network (decorative)",
    login_panel_connected: "Connected", login_panel_sent: "Alert sent", login_panel_dialing: "Dialing…", login_panel_signal: "Signal OK",
    login_flow_device: "IoT device", login_flow_gateway: "4G gateway", login_flow_people: "Call people",
    overview_title: "System overview", overview_sub: "System status and today's call summary",
    stat_calls: "Calls today", stat_calls_sub: "since midnight",
    stat_rate: "Success rate", stat_rate_sub: (ok: number, total: number) => `${ok} of ${total} calls`,
    stat_rate_none: "No calls yet today",
    stat_queue: "In queue", stat_queue_sub: "active jobs",
    recent_title: "Recent activity", recent_sub: "Last 5 entries", realtime: "Real-time", sample_data: "Sample data",
    outcome_title: "Today's call outcomes", outcome_empty: "No calls yet today",
    outcome_sub: (n: number) => `out of ${n} calls`,
    system_info_title: "System info", system_info_worker: "Call worker",
    system_info_worker_running: "Running", system_info_worker_stopped: "Not started",
    system_info_uptime: "Uptime", system_info_gsm: "GSM module", system_info_gsm_port: "Port",
    system_info_db_size: "Database size", system_info_version: "Version",
    device_pi_label: "Raspberry Pi", device_gsm_label: "GSM Module",
    device_view_detail: "Tap for details",
    gsm_detail_title: "GSM Module Details", gsm_mode_label: "Network mode", gsm_operator_label: "Carrier",
    gsm_signal_label: "Signal strength", gsm_signal_unknown: "Unknown", gsm_no_operator: "No signal",
    gsm_signal_excellent: "Excellent", gsm_signal_good: "Good", gsm_signal_fair: "Fair", gsm_signal_poor: "Weak",
    dash_signal_fix: "Open system page",
    gsm_status_ok: "Online", gsm_status_error: "Signal issue",
    pi_detail_title: "Raspberry Pi Details", pi_cpu_label: "CPU usage", pi_ram_label: "RAM usage",
    pi_temp_label: "CPU temperature", pi_temp_unavailable: "Not available on this device",
    widget_title: "Call alert status",
    widget_idle: "Waiting", widget_active: "Calling...", widget_success: "Call succeeded", widget_failed: "No answer — retrying",
    queue_title: "Call Queue", queue_sub: "Pending and in-progress jobs", queue_live: "Live",
    queue_empty: "Queue is empty", queue_empty_sub: "No jobs pending at this time",
    queue_legend_title: "What each status means",
    col_id: "Job ID", col_group: "Group", col_phone: "Phone", col_status: "Status",
    col_retry: "Retries", col_created: "Created", col_datetime: "Date / Time", col_note: "Note",
    history_title: "Call History", history_records: (n: number) => `${n} records total`,
    search_ph: "Search message or job ID…", search_short: "Search…",
    all_status: "All statuses", all_groups: "All groups", clear: "Clear",
    filters_btn: "Filters", filters_title: "Filters", filters_apply: "Apply filters", filters_reset: "Clear filters",
    no_data: "No records found", page_of: (p: number, t: number) => `Page ${p} of ${t}`,
    prev: "← Previous", next: "Next →",
    filter_status: "Status", filter_group: "Recipient group",
    settings_title: "Settings", settings_sub: "Call behavior and fallback options",
    retry_section: "Retry behavior", retry_section_sub: "Configure retry count and timing",
    answer_delay: "Pause before speaking",
    answer_delay_help: "How long to wait after the call is answered before speaking. The person needs a moment to raise the phone; speaking instantly loses the first sentence.",
    answer_delay_example: (n: number) =>
      n === 0 ? "0 = start speaking the instant they answer, risking the first sentence" : `${n}s → answered at 10:00:00, speech starts at 10:00:${String(n).padStart(2, "0")}`,
    repeat_count: "Repeat the message",
    repeat_count_help: "How many times to repeat the same message in one call. One pass is often not enough to catch everything, especially half-asleep or somewhere noisy.",
    repeat_count_example: (n: number) =>
      n === 1 ? "1 = say it once, then hang up" : `${n} = repeat ${n} times, 1.5s apart · stops early if they hang up`,
    retry_count: "Retry count", retry_count_sub: "Maximum retries before marking as failed",
    retry_delay: "Delay before retry", retry_delay_sub: "How long to wait before redialing",
    ring_timeout: "Ring timeout", ring_timeout_sub: "How long to wait for an answer before hanging up",
    unit_times: "times", unit_seconds: "seconds", unit_minutes: "minutes",
    sys_theme_light: "Light", sys_theme_dark: "Dark",
    ov_success: "Success", ov_failed: "Failed", ov_done_today: "Done today",
    ov_live_queue: "Live queue", ov_jobs: "jobs",
    ov_queue_empty: "Queue empty — ready for work",
    ov_col_name_phone: "Name / Phone", ov_col_time: "Time",
    ov_health: "System health",
    ov_health_ok: "OK", ov_health_high: "High", ov_health_critical: "Critical",
    ov_axis_max: (n: number) => `peak ${n}/hr`,
    ov_health_scale_ok: (hi: number) => `OK under ${hi}%`,
    ov_health_scale_high: (lo: number, hi: number) => `High ${lo}–${hi}%`,
    ov_health_scale_critical: (lo: number) => `Critical from ${lo}%`,
    ov_hour_calls: (hour: string, n: number) => `${hour} — ${n} call${n === 1 ? "" : "s"}`,
    ov_temp: "Temp", ov_peak: "Peak hour",
    ov_peak_at: (h: string, n: number) => `${h} · ${n} calls`,
    ov_no_peak: "No calls yet today",
    duration_range: (lo: number, hi: number) =>
      `Allowed: ${formatDurationEn(lo)} to ${formatDurationEn(hi)}`,
    count_range: (lo: number, hi: number, unit: string) => `Allowed: ${lo} to ${hi} ${unit}`,
    cfg_example_label: "Example",
    setup_title: "Alert setup",
    setup_sub: "Groups · Event types · Devices & keys",
    setup_tab_devices: "Devices & keys", setup_tab_events: "Event types", setup_tab_contacts: "Contact groups",
    et_used_by: "Used by",
    et_used_by_count: (n: number) => `${n} device${n !== 1 ? "s" : ""}`,
    et_used_by_none: "— not used yet —",
    event_type_delete_in_use: (n: number) =>
      `${n} device${n !== 1 ? "s" : ""} currently use this event. Deleting it means they can no longer trigger it (past call history is kept).`,
    dev_call_group_none: "— pick a group —",
    /* ── New devices page: list on the left, settings on the right ────── */
    dv_search_ph: "Search device name or key",
    dv_count_all: "{n} devices",
    dv_count_found: "{n} of {all} devices",
    dv_pill_ready: "Ready",
    dv_pill_off: "Disabled",
    dv_pill_noevent: "No events enabled",
    dv_pill_notarget: "No one to call",
    dv_active_on: "Enabled",
    dv_active_off: "Disabled",
    dv_off_banner: "This device is disabled — reports will not trigger a call. The settings below are kept.",
    dv_events_on: "Enabled events",
    dv_add_event: "Add event",
    dv_add_event_title: "Add an event to this device",
    dv_add_event_ph: "— pick an event —",
    dv_add_event_hint: "You still need to set who gets called, otherwise reports are rejected",
    dv_add_event_none: "This device already has every event type in the system",
    dv_no_events_yet: "No events enabled yet — anything this device sends will be rejected",
    dv_recip_group: "Group:",
    dv_recip_custom: "{n} specific contacts",
    dv_recip_none: "No recipients set",
    dv_configure: "Set up",
    dv_key_show: "Show", dv_key_hide: "Hide",
    dv_mode_group_desc: "Dials down the group in order — if the first doesn't answer, the next one is called",
    dv_mode_custom_desc: "Pick people individually, across groups. The number shown is the call order.",
    dv_pick_group: "Pick the group to call",
    dv_search_recip_ph: "Search group, name, or number",
    dv_search_none: "Nothing matches your search",
    dv_col_people: "Members", dv_col_person: "Name", dv_col_in_group: "In group",
    dv_col_order: "Order",
    dv_no_groups: "No contact groups yet — create one on the Contact groups tab first",
    dv_remove_event_confirm: "Remove this event from the device? Its recipient setting is lost and the device can no longer trigger it.",
    dv_delete_device_confirm: "Delete this device? Its key stops working immediately and cannot be recovered — past call history is kept.",
    dv_no_events: "No event types exist yet — create one on the Event types tab first",
    dv_saving: "Saving…",
    dev_target_mode: "Recipients",
    dev_target_group: "Whole group",
    dev_target_contacts: "Pick numbers",
    dev_target_missing: "No recipients picked — requests for this event will be rejected",
    dev_pick_contacts_hint: "Tick only the people you need, across any group. Tick order is the escalation order (adjustable below).",
    dev_no_contacts_at_all: "No phone numbers in the system yet — add some on the contact groups page first.",
    dev_call_order: "Call order",
    dev_will_call: "calls",
    dev_group_empty: "this group has no numbers yet",
    move_up: "Move up", move_down: "Move down",
    dev_key_full: "This device's full key",
    dev_key_locked: "This device predates key storage — only the prefix is visible. Create a new device if you need the full key.",
    dev_api_title: "How this device sends alerts",
    dev_api_sub: "Everything the board needs is here — no need to open the API guide",
    dev_api_key_note: "This command already contains the real key — paste it straight into the firmware. Never share it or commit it to a public repo.",
    dev_api_no_event: "Pick the events this device may send first, and the examples will follow",
    dev_api_ok: "Success response", dev_api_err: "Error response",
    dev_api_status: "Common status codes",
    dev_api_status_400: "No recipients picked for this event, or the chosen group has no numbers",
    dev_api_status_401: "Wrong key, or the device was deleted",
    dev_api_status_403: "Key is valid but this event is not allowed — tick it on the left",
    dev_api_status_404: "No event type with that code",
    dev_api_status_422: "Missing X-API-Key header, or malformed JSON",
    cfg_saving: "Saving…", cfg_saved: "Saved", cfg_save_failed: "Could not save",
    gsm_restart: "Restart module", gsm_restarting: "Restarting…",
    gsm_restart_confirm_title: "Restart the 4G module?",
    gsm_restart_confirm_body: "The radio is switched off and on, then re-registers on the network. Takes about 10-30 seconds, during which no calls can be placed. Queued jobs are dialed once it is back, and any call in progress is always allowed to finish first.",
    gsm_restart_hint: "Use when signal is lost, the network cannot be found, or the module stops responding",
    gsm_restart_ok: "Module restarted and back on the network",
    gsm_restart_failed: "Restarted but not registered yet — check the SIM and antenna",
    gsm_restart_sent: "Command sent, waiting for the module to come back",
    retry_count_help: "If the first contact does not answer, how many more times to redial the same number before moving on to the next contact in the group.",
    retry_count_example: (n: number) =>
      n === 0
        ? "0 = never redial — move to the next contact immediately (best when speed matters most)"
        : `${n} → the first number is dialed ${n + 1} times total (first attempt + ${n} retries) before contact 2 is tried`,
    retry_delay_help: "How long to wait before redialing. The system is not idle during this time — it picks up other queued jobs meanwhile.",
    retry_delay_example: (n: number) =>
      `${formatDurationEn(n)} → no answer at 10:00:00, redial happens at ${clockAfter(n)}`,
    ring_timeout_help: "How long to let the phone ring before giving up. Too short and nobody can pick up; too long and the queue moves slowly.",
    ring_timeout_example: (n: number) =>
      `${formatDurationEn(n)} → rings for ${formatDurationEn(n)} with no answer, then hangs up and counts as one "no answer"`,
    call_budget_title: "Worst case per contact",
    call_budget: (sec: number, tries: number) =>
      `${formatDurationEn(sec)} per contact — ${tries} attempts before moving to the next one`,
    save_btn: "Save settings", save_ok: "Settings saved successfully",
    contacts_title: "Notification groups",
    contacts_sub: "Called top to bottom — if the first person doesn't pick up, the next one is called",
    add_group: "Add group", new_group: "New notification group", new_group_ph: "e.g. Technical team", create: "Create group",
    group_name_label: "Group name",
    new_group_hint: "Name it so anyone reading it knows who it is — this name shows up when picking who a device calls. Add numbers once the group exists.",
    contacts_search: "Search group, person, or phone number",
    contacts_search_none: "No group, name, or number matches your search",
    contacts_search_found: (n: number) => `${n} group${n !== 1 ? "s" : ""} match`,
    no_phones: "No phone numbers yet — add one below", phone_ph: "0812345678",
    contact_name_ph: "Who answers this number", edit_group_name: "Rename group",
    phones_count: (n: number) => `${n} number${n !== 1 ? "s" : ""}`,
    group_delete_confirm: "Delete this group? All its phone numbers will be removed too.",
    ct_people_count: (n: number) => `${n} ${n === 1 ? "person" : "people"}`,
    ct_col_phones: "Numbers", ct_col_members: "Who gets called",
    ct_edit_group: "Edit contact group",
    ct_members: "Members",
    ct_order_hint: "(order = the order they are actually called)",
    ct_add_member: "Add member",
    ct_member_hint: "Both name and phone are required — incomplete rows are not saved. The name is what people read during a real incident.",
    contact_delete_confirm: "Remove this number from the group? Everyone below moves up in the call order.",
    api_title: "API Guide", api_sub: "Reference documentation for external integrations",
    guide_title: "User guide", guide_sub: "How to set it up, how to read the results, and how devices send alerts",
    guide_tab_usage: "How to use", guide_tab_api: "Developer API",
    api_key_section: "API key", api_key_warn: "Never expose this API key publicly. Always pass it via an environment variable or secret manager.",
    copy: "Copy", copied: "Copied",
    copy_failed: "Copy failed — select the text and copy it manually",
    endpoint_title: "POST /notify",
    endpoint_desc: "Queue a call alert by event type code. The system dials numbers in the escalation order of the linked group.",
    curl_title: "Example curl request", resp_title: "Example response",
    manage_keys_hint: "Manage real API keys on the",
    api_quickstart_title: "Get started in 3 steps",
    qs_step1_title: "Create an event type", qs_step1_desc: "Define a code, message, and recipient group",
    qs_step2_title: "Generate an API key", qs_step2_desc: "So external systems can authenticate",
    qs_step3_title: "Call the endpoint", qs_step3_desc: "Send POST /notify with your API key",
    request_body_title: "Request body", response_title: "Response",
    resp_field_job_id_desc: "The queued job's ID — use it to check status later",
    resp_field_status_desc: "The job's initial status (usually queued)",
    resp_field_message_desc: "Confirmation message for display",
    code_examples_title: "Code examples", error_resp_title: "Example error response",
    base_url_note: "Replace https://your-pi.local with your device's actual network address.",
    base_url_label: "Base URL", request_body_json_label: "Request body (JSON)",
    col_parameter: "Parameter", col_required: "Required", col_type: "Type", col_description: "Description",
    status_codes_title: "HTTP status codes",
    status_200_desc: "Request succeeded — the job has been queued",
    status_400_desc: "The request is well-formed but can't be processed, e.g. the event type is disabled or the template needs a variable you didn't send",
    status_401_desc: "The API key is invalid or has been revoked (omitting the X-API-Key header entirely returns 422 instead)",
    status_404_desc: "No event type matches the given code",
    status_422_desc: "The request body is malformed, e.g. event_type_code is missing or has the wrong type (checked automatically)",
    status_500_desc: "An internal error occurred — please try again",
    badge_success: "Success", badge_failed: "Failed", badge_retrying: "Retrying",
    badge_calling: "Calling", badge_queued: "Queued",
    badge_no_answer: "No answer", badge_busy: "Busy", badge_escalated: "Next contact",
    pi_label: "Raspberry Pi", tower_label: "4G Signal", phone_label: "Call alert",
    required: "required", optional: "optional",
    loading: "Loading...", error_generic: "Something went wrong, please try again", retry_action: "Retry",
    cancel: "Cancel", save: "Save", saving: "Saving...", delete: "Delete", edit: "Edit", close: "Close",
    confirm: "Confirm", yes_delete: "Yes, delete",
    event_types_title: "Event Types",
    event_types_sub: "What can be reported, and the sentence spoken on the call",
    add_event_type: "Add event type", new_event_type: "New event type", edit_event_type: "Edit event type",
    code_label: "Code", code_ph: "e.g. power_outage", code_hint: "Lowercase letters, numbers and _ only. Cannot be changed later.",
    display_name_label: "Display name", display_name_ph: "e.g. Power outage",
    message_template_label: "Message template", message_template_ph: "e.g. Power outage at {location} at {value}",
    message_template_hint: "Use {variable_name} for values the device sends at alert time, e.g. {temp}",
    et_vars_title: "Variables in this message",
    et_vars_none: "No variables yet — the message is spoken exactly as written. To include a live reading, add {temp} to the text.",
    et_vars_send: "the device must send",
    et_howto_title: "How to use it",
    et_vars_example: "Example request body",
    et_vars_missing: "If the device omits a value the request is rejected right away (400), not queued",
    et_limits_title: "Limits",
    et_limit_msg: "Message ≤ 500 characters",
    et_limit_count: "At most 20 variables",
    et_limit_value: "Each value ≤ 200 characters",
    group_label: "Recipient group",
    col_code: "Code", col_name: "Display name", col_active: "Status", col_actions: "Actions",
    send_test: "Send test", test_dialog_title: "Send a test notification",
    test_variables_label: "Variables", test_variables_hint: "One key=value per line",
    test_message_override_label: "Message (optional — leave blank to use the template)",
    send: "Send", sending: "Sending...", test_sent_ok: (id: number) => `Test notification queued — job #${id}`,
    delete_confirm_title: "Confirm delete", event_type_delete_confirm: "Delete this event type?",
    code_exists_error: "This code already exists", no_event_types: "No event types yet",
    api_keys_title: "API Keys", api_keys_sub: "Manage keys used by external systems calling /notify",
    add_key: "Create new key", new_key_name_label: "Key name", new_key_name_ph: "e.g. Monitoring board",
    key_created_title: "API key created", key_created_warning: "Copy this key now — it will never be shown again.",
    key_prefix_label: "Key", last_used_label: "Last used", created_label: "Created", revoked_label: "Revoked",
    status_active: "Active", status_revoked: "Revoked", never: "Never used",
    revoke: "Delete", revoke_confirm_title: "Confirm delete", revoke_confirm_body: "Delete this device? Its key stops working immediately and cannot be recovered (past call history is kept).",
    no_api_keys: "No API keys yet",
    filter_date_from: "From date", filter_date_to: "To date",
    toast_created: "Created successfully", toast_updated: "Updated successfully", toast_deleted: "Deleted successfully",

    // ─── Devices (1 key = 1 device) ───
    devices_title: "Devices & keys",
    devices_sub: "Machines allowed to report in — each has its own password, set once",
    devices_summary: (n: number, active: number) => `${n} devices · ${active} active`,
    add_device: "Add device",
    device_name_label: "Device name",
    device_name_ph: "e.g. Node Building A Floor 3",
    device_name_hint: "Identifies the source in the call history and queue — editable later, not spoken in the call",
    device_search: "Search device name", device_search_none: "No device matches your search",
    device_configure: "Configure",
    device_test_call: "Test call",
    device_remove: "Delete device",
    device_remove_confirm: "Click again to confirm",
    device_view: "View",
    device_ready: "Ready", device_not_ready_events: "No events set",
    device_not_ready_recipients: "No recipients", device_off: "Off",
    device_toggle_label: "Status",
    device_toggle_on_hint: "On — alerts are accepted normally",
    device_toggle_off_hint: "Off — incoming alerts are rejected, but the key is kept",
    device_last_alert_label: "Last alert",
    device_events_section: "Can report → calls",
    device_last_alert: (d: string) => `Last alert ${d}`,
    device_never_alerted: "No alerts yet",
    device_stat_events: "Can report", device_stat_recipients: "Calls",
    device_events_value: (n: number) => `${n} event${n === 1 ? "" : "s"}`,
    device_recipients_groups: (n: number) => `${n} group${n === 1 ? "" : "s"}`,
    device_recipients_phones: (n: number) => `${n} number${n === 1 ? "" : "s"}`,
    device_recipients_mixed: (g: number, p: number) =>
      `${g} group${g === 1 ? "" : "s"} + ${p} number${p === 1 ? "" : "s"}`,
    device_recipients_none: "Not set",
    devices_empty_title: "No devices yet",
    devices_empty_body: "Create the first key so a board can send alerts in",

    allowed_events_label: "Allowed alerts",
    allowed_events_none: "No permissions yet — anything this device sends will be rejected (403)",
    allowed_events_pick: "Pick the event types this device may trigger",
    event_filter: "Search events", event_filter_none: "No event matches your search",
    event_picked_count: (n: number, total: number) => `${n} of ${total} selected`,
    dev_api_more: "Full reference in the API guide",
    allowed_events_empty_hint: "No event types exist yet — create one on the Event Types page first",

    add_device_sub: "Create the password for one device — the board uses it to identify itself when reporting",
    add_device_step1: "Name & events", add_device_step2: "Get the key",
    events_selected: (n: number) => `${n} selected`,
    events_select_all: "Select all", events_clear: "Clear all",
    key_example_label: "What the board must send",
    key_once_title: "This key is shown once",
    key_once_body: "Copy it into the firmware now — once you close this you cannot see it again (only a hash is stored)",
    key_no_copy_hint: "Only the key prefix is visible because the server stores a hash, not the full key",
    save_and_configure: "Save and configure",
    save_only: "Save for now",
    done: "Done",

    device_config_title: "Device settings",
    what_will_happen: "What happens when this device reports",
    what_will_happen_empty: "No alert permissions granted yet",
    payload_title: "Payload the device must send",
    shared_config_note: "Recipients and message text are shared per event type — editing them affects every device using that type",
    goto_event_types: "Edit event type",
    goto_contacts: "Edit groups",
    // ─── Signal Flow Monitor ───
    flow_title: "Signal Flow Monitor",
    flow_node_api: "API Gateway",
    flow_node_pi: "Raspberry Pi",
    flow_node_antenna: "4G Tower",
    flow_node_phone: "Phone",
    flow_step_preparing: "Generating speech",
    flow_step_uploading: "Uploading audio to module",
    flow_step_dialing: "Dialing, waiting for answer",
    flow_step_playing: "Answered, playing message",
    flow_step_waiting_retry: "Call failed, waiting to retry",
    flow_result_rejected: "Call rejected — retrying soon",
    flow_result_no_answer: "No answer — retrying soon",
    flow_result_busy: "Line busy — retrying soon",
    flow_cap_received: "Request received",
    flow_cap_tts: "Generating speech",
    flow_cap_upload: "Uploading to module",
    flow_cap_dialing: "Connecting call",
    flow_cap_playing: "Playing message",
    flow_cap_retry: "Waiting to retry",
    flow_cap_idle: "Waiting for a request",
    flow_state_idle: "Idle",
    flow_state_calling: "Dialing",
    flow_state_ringing: "Ringing / waiting retry",
    flow_state_success: "Answered",
    flow_state_failed: "Failed",
    flow_gsm_offline: "Module not connected",
    flow_source: (n: number) => `${n} in queue`,
    flow_step_note: "Per-step timing (payload received → key checked → dial → answered → audio finished) needs a GET /history/{job_id} endpoint. This currently derives from the latest job status only.",
    flow_layout_style: "Layout style",
    module_ready: "Online", module_not_ready: "Offline", sign_out_short: "Sign out",
    dash_last_update: (t: string) => `Updated ${t}`,
    dash_refresh_every: (s: number) => `Auto-refresh every ${s}s`,
    pipe_title: "Pipeline now", pipe_flow: "payload → key check → queue → call → result",
    pipe_queued: "Queued", pipe_calling: "Dialing", pipe_retry: "Awaiting retry", pipe_done: "Finished today",
    pipe_queued_sub: "waiting for worker", pipe_calling_sub: "on the line", pipe_retry_sub: "next round", pipe_done_sub: "all outcomes",
    pipe_none: "empty",
    flow_signal_step: "SIGNAL STEP",
    flow_auto: "Auto", flow_demo_mode: "demo", flow_incoming_requests: "INCOMING REQUESTS",
    flow_badge_working: "working", flow_badge_queued: (n: number) => `${n} queued`,
    flow_req: (n: number) => `${n} req`,
    flow_demo_note: "Demo mode — the view is forced to this state and does not reflect the real system.",
    flow_time_unknown: "No per-step timing yet",
    flow_legend_done: "Done", flow_legend_active: "In progress", flow_legend_ringing: "Ringing",
    flow_legend_failed: "Failed", flow_legend_pending: "Not yet",
    flow_open_settings: "Go to call settings",
    flow_steps: ["Request in", "Key check", "Speech built", "Ready to send",
      "Module linked", "Audio upload", "Dialing", "Answered"],
    flow_step_aria: (n: number, name: string) => `Step ${n} of 8 · ${name}`,
    flow_all_steps_done: "All 8 steps complete",
    api_base_label: "base",
    api_notes_title: "Good to know",
    api_note_1: "Every placeholder in the message must be supplied in variables, {device} included — a missing one is rejected with 400",
    api_note_2: "Recipients and message text can be changed later without touching the firmware",
    api_note_3: "On a 403, grant that device permission for the event type on the Devices page",
    api_note_4: "The key is shown once at creation. If lost, delete the device and create a new one (requires reflashing)",
    sys_section_hw: "Hardware", sys_section_call: "Call settings", sys_section_app: "App & account",


    // ─── System & hardware ───
    sys_title: "System & hardware",
    sys_meta: "4G module · Raspberry Pi · runtime · call settings",
    sys_module_4g: "4G module",
    sys_module_offline: "Not connected",
    sys_module_power: "Module power", sys_module_power_on: "On", sys_module_power_off: "Off",
    sys_module_port: "Port",
    sys_module_updated: "Last updated",
    sys_pi_title: "Raspberry Pi",
    sys_call_config: "Call settings",
    sys_call_config_note: "Saved automatically on every change — the worker picks up new values within seconds, no restart needed",
    sys_runtime: "Runtime",
    sys_theme_label: "Page theme",
    sys_theme_to_light: "Switch to light",
    sys_theme_to_dark: "Switch to dark",

    // ─── Call log ───
    log_filter_all: "All",
    log_filter_ok: "Answered",
    log_filter_no_answer: "No answer",
    log_filter_failed: "Failed",
    log_export_csv: "Export CSV",
    log_export_note: "Exports the current page only",
    log_date_from: "From", log_date_to: "To",
    log_date_today: "Today", log_date_7d: "7 days", log_date_30d: "30 days",
    log_date_yesterday: "Yesterday", log_date_this_month: "This month",
    log_pick_month: "Month",
    log_day_calls: (n: number) => `${n} call${n === 1 ? "" : "s"}`,
    log_clear_range: "Show all",
    log_date_all: "All time", log_date_custom: "Custom",
    log_group_status: "Result", log_group_range: "Presets", log_group_custom: "Custom",
    log_col_device: "Device",
    log_col_event: "Event",
    log_empty: "No records match the selected filter",
    log_range: (from: number, to: number, total: number) => `${from}–${to} / ${total}`,

    // ─── Dashboard ───
    dash_auto_refresh: "Auto-refresh every 5s",
    dash_signal_4g: "4G signal",
    dash_success_fail: "Success / failed",
    dash_tap_row_hint: "Tap a row for details",
    dash_view_all: "View all",
    dash_calls_24h: "Calls over 24h",
    dash_spoken: "Spoken message",
    dash_no_events: "No events yet",
    dash_detail_note: "The full per-step timeline (payload received → key checked → dial → answered → audio finished) needs a GET /history/{job_id} endpoint. This shows what /history returns today.",
    dash_last_attempt: "Last attempt",
    dash_retry_count: "Retries so far",
    dash_contact_index: "Contact index",
    dash_hours_capped: "Counted from the latest 100 records of today",

    retry_summary: (count: number, delay: number) => `No answer → retry ${count} times, ${delay}s apart`,
    escalate_summary: "Still no answer after retries → move to the next number in the group",
  },
} as const;

export type Tr = typeof TR.th;

// ─── App context ──────────────────────────────────────────────────────────────

export interface AppCtx {
  T: Tr;
  dark: boolean;
  toggleDark: () => void;
  lang: Lang;
  toggleLang: () => void;
}

export const Ctx = createContext<AppCtx>(null!);
export const useApp = () => useContext(Ctx);

const LANG_STORAGE_KEY = "gateway_lang";
const DARK_STORAGE_KEY = "gateway_dark";

function getStoredLang(): Lang {
  const stored = localStorage.getItem(LANG_STORAGE_KEY);
  return stored === "en" ? "en" : "th";
}

function getStoredDark(): boolean {
  const stored = localStorage.getItem(DARK_STORAGE_KEY);
  if (stored !== null) return stored === "true";
  return window.matchMedia?.("(prefers-color-scheme: dark)").matches ?? false;
}

export function AppProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(getStoredLang);
  const [dark, setDark] = useState<boolean>(getStoredDark);

  const T = TR[lang] as Tr;
  const toggleDark = () => setDark((d) => !d);
  const toggleLang = () => setLang((l) => (l === "th" ? "en" : "th"));

  useEffect(() => {
    document.documentElement.classList.toggle("dark", dark);
    // ต้องใส่ .light ด้วย ไม่ใช่แค่ถอด .dark — theme.css มี @media (prefers-color-scheme: dark)
    // ที่ยิงใส่ :root:not(.light) ถ้าไม่มีคลาสนี้ เครื่องที่ตั้ง OS เป็น dark ไว้
    // จะถูกบังคับเป็น dark ทับการเลือก light ของผู้ใช้
    document.documentElement.classList.toggle("light", !dark);
    localStorage.setItem(DARK_STORAGE_KEY, String(dark));
  }, [dark]);

  useEffect(() => {
    localStorage.setItem(LANG_STORAGE_KEY, lang);
  }, [lang]);

  const ctx: AppCtx = { T, dark, toggleDark, lang, toggleLang };

  return <Ctx.Provider value={ctx}>{children}</Ctx.Provider>;
}
